<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdNewsZhidingLog', 'trade');

/**
 * BaseTrdNewsZhidingLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $newsid
 * @property integer $type
 * @property timestamp $zhiding_at
 * 
 * @method integer           getId()         Returns the current record's "id" value
 * @method integer           getNewsid()     Returns the current record's "newsid" value
 * @method integer           getType()       Returns the current record's "type" value
 * @method timestamp         getZhidingAt()  Returns the current record's "zhiding_at" value
 * @method TrdNewsZhidingLog setId()         Sets the current record's "id" value
 * @method TrdNewsZhidingLog setNewsid()     Sets the current record's "newsid" value
 * @method TrdNewsZhidingLog setType()       Sets the current record's "type" value
 * @method TrdNewsZhidingLog setZhidingAt()  Sets the current record's "zhiding_at" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdNewsZhidingLog extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_news_zhiding_log');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('newsid', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('zhiding_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}