<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdProductAttr', 'trade');

/**
 * BaseTrdProductAttr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $news_id
 * @property integer $goods_id
 * @property string $title
 * @property string $name
 * @property string $url
 * @property string $img_path
 * @property string $intro
 * @property string $memo
 * @property float $price
 * @property float $exchange
 * @property float $original_cost
 * @property float $freight
 * @property float $business_weight
 * @property float $weight
 * @property integer $limits
 * @property string $content
 * @property string $business
 * @property integer $start_date
 * @property integer $end_date
 * @property integer $crawl_flag
 * @property integer $show_flag
 * @property integer $root_id
 * @property integer $children_id
 * @property integer $brand_id
 * @property integer $hits
 * @property integer $praise
 * @property string $external_username
 * @property integer $last_crawl_date
 * @property integer $display
 * @property integer $status
 * @property integer $author_id
 * @property integer $editor_id
 * @property timestamp $publish_date
 * @property integer $purchase_flag
 * @property integer $purchase_uid
 * @property string $purchase_msg
 * @property integer $purchase_date
 * @property integer $dace_hits
 * @property integer $dace_buy_hits
 * @property integer $comment_count
 * @property integer $comment_count_img
 * @property string $tags_attr
 * @property float $discount
 * @property timestamp $discount_endtime
 * @property integer $collect_count
 * @property integer $shaiwu_count
 * @property string $commodity
 * 
 * @method integer        getId()                Returns the current record's "id" value
 * @method integer        getNewsId()            Returns the current record's "news_id" value
 * @method integer        getGoodsId()           Returns the current record's "goods_id" value
 * @method string         getTitle()             Returns the current record's "title" value
 * @method string         getName()              Returns the current record's "name" value
 * @method string         getUrl()               Returns the current record's "url" value
 * @method string         getImgPath()           Returns the current record's "img_path" value
 * @method string         getIntro()             Returns the current record's "intro" value
 * @method string         getMemo()              Returns the current record's "memo" value
 * @method float          getPrice()             Returns the current record's "price" value
 * @method float          getExchange()          Returns the current record's "exchange" value
 * @method float          getOriginalCost()      Returns the current record's "original_cost" value
 * @method float          getFreight()           Returns the current record's "freight" value
 * @method float          getBusinessWeight()    Returns the current record's "business_weight" value
 * @method float          getWeight()            Returns the current record's "weight" value
 * @method integer        getLimits()            Returns the current record's "limits" value
 * @method string         getContent()           Returns the current record's "content" value
 * @method string         getBusiness()          Returns the current record's "business" value
 * @method integer        getStartDate()         Returns the current record's "start_date" value
 * @method integer        getEndDate()           Returns the current record's "end_date" value
 * @method integer        getCrawlFlag()         Returns the current record's "crawl_flag" value
 * @method integer        getShowFlag()          Returns the current record's "show_flag" value
 * @method integer        getRootId()            Returns the current record's "root_id" value
 * @method integer        getChildrenId()        Returns the current record's "children_id" value
 * @method integer        getBrandId()           Returns the current record's "brand_id" value
 * @method integer        getHits()              Returns the current record's "hits" value
 * @method integer        getPraise()            Returns the current record's "praise" value
 * @method string         getExternalUsername()  Returns the current record's "external_username" value
 * @method integer        getLastCrawlDate()     Returns the current record's "last_crawl_date" value
 * @method integer        getDisplay()           Returns the current record's "display" value
 * @method integer        getStatus()            Returns the current record's "status" value
 * @method integer        getAuthorId()          Returns the current record's "author_id" value
 * @method integer        getEditorId()          Returns the current record's "editor_id" value
 * @method timestamp      getPublishDate()       Returns the current record's "publish_date" value
 * @method integer        getPurchaseFlag()      Returns the current record's "purchase_flag" value
 * @method integer        getPurchaseUid()       Returns the current record's "purchase_uid" value
 * @method string         getPurchaseMsg()       Returns the current record's "purchase_msg" value
 * @method integer        getPurchaseDate()      Returns the current record's "purchase_date" value
 * @method integer        getDaceHits()          Returns the current record's "dace_hits" value
 * @method integer        getDaceBuyHits()       Returns the current record's "dace_buy_hits" value
 * @method integer        getCommentCount()      Returns the current record's "comment_count" value
 * @method integer        getCommentCountImg()   Returns the current record's "comment_count_img" value
 * @method string         getTagsAttr()          Returns the current record's "tags_attr" value
 * @method float          getDiscount()          Returns the current record's "discount" value
 * @method timestamp      getDiscountEndtime()   Returns the current record's "discount_endtime" value
 * @method integer        getCollectCount()      Returns the current record's "collect_count" value
 * @method integer        getShaiwuCount()       Returns the current record's "shaiwu_count" value
 * @method string         getCommodity()         Returns the current record's "commodity" value
 * @method TrdProductAttr setId()                Sets the current record's "id" value
 * @method TrdProductAttr setNewsId()            Sets the current record's "news_id" value
 * @method TrdProductAttr setGoodsId()           Sets the current record's "goods_id" value
 * @method TrdProductAttr setTitle()             Sets the current record's "title" value
 * @method TrdProductAttr setName()              Sets the current record's "name" value
 * @method TrdProductAttr setUrl()               Sets the current record's "url" value
 * @method TrdProductAttr setImgPath()           Sets the current record's "img_path" value
 * @method TrdProductAttr setIntro()             Sets the current record's "intro" value
 * @method TrdProductAttr setMemo()              Sets the current record's "memo" value
 * @method TrdProductAttr setPrice()             Sets the current record's "price" value
 * @method TrdProductAttr setExchange()          Sets the current record's "exchange" value
 * @method TrdProductAttr setOriginalCost()      Sets the current record's "original_cost" value
 * @method TrdProductAttr setFreight()           Sets the current record's "freight" value
 * @method TrdProductAttr setBusinessWeight()    Sets the current record's "business_weight" value
 * @method TrdProductAttr setWeight()            Sets the current record's "weight" value
 * @method TrdProductAttr setLimits()            Sets the current record's "limits" value
 * @method TrdProductAttr setContent()           Sets the current record's "content" value
 * @method TrdProductAttr setBusiness()          Sets the current record's "business" value
 * @method TrdProductAttr setStartDate()         Sets the current record's "start_date" value
 * @method TrdProductAttr setEndDate()           Sets the current record's "end_date" value
 * @method TrdProductAttr setCrawlFlag()         Sets the current record's "crawl_flag" value
 * @method TrdProductAttr setShowFlag()          Sets the current record's "show_flag" value
 * @method TrdProductAttr setRootId()            Sets the current record's "root_id" value
 * @method TrdProductAttr setChildrenId()        Sets the current record's "children_id" value
 * @method TrdProductAttr setBrandId()           Sets the current record's "brand_id" value
 * @method TrdProductAttr setHits()              Sets the current record's "hits" value
 * @method TrdProductAttr setPraise()            Sets the current record's "praise" value
 * @method TrdProductAttr setExternalUsername()  Sets the current record's "external_username" value
 * @method TrdProductAttr setLastCrawlDate()     Sets the current record's "last_crawl_date" value
 * @method TrdProductAttr setDisplay()           Sets the current record's "display" value
 * @method TrdProductAttr setStatus()            Sets the current record's "status" value
 * @method TrdProductAttr setAuthorId()          Sets the current record's "author_id" value
 * @method TrdProductAttr setEditorId()          Sets the current record's "editor_id" value
 * @method TrdProductAttr setPublishDate()       Sets the current record's "publish_date" value
 * @method TrdProductAttr setPurchaseFlag()      Sets the current record's "purchase_flag" value
 * @method TrdProductAttr setPurchaseUid()       Sets the current record's "purchase_uid" value
 * @method TrdProductAttr setPurchaseMsg()       Sets the current record's "purchase_msg" value
 * @method TrdProductAttr setPurchaseDate()      Sets the current record's "purchase_date" value
 * @method TrdProductAttr setDaceHits()          Sets the current record's "dace_hits" value
 * @method TrdProductAttr setDaceBuyHits()       Sets the current record's "dace_buy_hits" value
 * @method TrdProductAttr setCommentCount()      Sets the current record's "comment_count" value
 * @method TrdProductAttr setCommentCountImg()   Sets the current record's "comment_count_img" value
 * @method TrdProductAttr setTagsAttr()          Sets the current record's "tags_attr" value
 * @method TrdProductAttr setDiscount()          Sets the current record's "discount" value
 * @method TrdProductAttr setDiscountEndtime()   Sets the current record's "discount_endtime" value
 * @method TrdProductAttr setCollectCount()      Sets the current record's "collect_count" value
 * @method TrdProductAttr setShaiwuCount()       Sets the current record's "shaiwu_count" value
 * @method TrdProductAttr setCommodity()         Sets the current record's "commodity" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdProductAttr extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_product_attr');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('news_id', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('goods_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 200,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 30,
             ));
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 200,
             ));
        $this->hasColumn('img_path', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('intro', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('memo', 'string', 20000, array(
             'type' => 'string',
             'length' => 20000,
             ));
        $this->hasColumn('price', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('exchange', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('original_cost', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('freight', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('business_weight', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('weight', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('limits', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('content', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
        $this->hasColumn('business', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('start_date', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('end_date', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('crawl_flag', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('show_flag', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('root_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('children_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('brand_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('hits', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('praise', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('external_username', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('last_crawl_date', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('display', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('author_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 8,
             ));
        $this->hasColumn('editor_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 8,
             ));
        $this->hasColumn('publish_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('purchase_flag', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('purchase_uid', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 8,
             ));
        $this->hasColumn('purchase_msg', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('purchase_date', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('dace_hits', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('dace_buy_hits', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('comment_count', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('comment_count_img', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('tags_attr', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('discount', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('discount_endtime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('collect_count', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             ));
        $this->hasColumn('shaiwu_count', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             ));
        $this->hasColumn('commodity', 'string', 511, array(
             'type' => 'string',
             'default' => '',
             'length' => 511,
             ));


        $this->index('name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->index('root_id', array(
             'fields' => 
             array(
              0 => 'root_id',
             ),
             ));
        $this->index('children_id', array(
             'fields' => 
             array(
              0 => 'children_id',
             ),
             ));
        $this->index('author_id', array(
             'fields' => 
             array(
              0 => 'author_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}