<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdActivitySet', 'trade');

/**
 * BaseTrdActivitySet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $key
 * @property string $role
 * @property string $note
 * @property string $remarks
 * @property integer $version
 * @property integer $status
 * 
 * @method integer        getId()      Returns the current record's "id" value
 * @method string         getKey()     Returns the current record's "key" value
 * @method string         getRole()    Returns the current record's "role" value
 * @method string         getNote()    Returns the current record's "note" value
 * @method string         getRemarks() Returns the current record's "remarks" value
 * @method integer        getVersion() Returns the current record's "version" value
 * @method integer        getStatus()  Returns the current record's "status" value
 * @method TrdActivitySet setId()      Sets the current record's "id" value
 * @method TrdActivitySet setKey()     Sets the current record's "key" value
 * @method TrdActivitySet setRole()    Sets the current record's "role" value
 * @method TrdActivitySet setNote()    Sets the current record's "note" value
 * @method TrdActivitySet setRemarks() Sets the current record's "remarks" value
 * @method TrdActivitySet setVersion() Sets the current record's "version" value
 * @method TrdActivitySet setStatus()  Sets the current record's "status" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdActivitySet extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_activity_set');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('key', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('role', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('note', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('remarks', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('version', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));


        $this->index('idx_key', array(
             'fields' => 
             array(
              0 => 'key',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}