<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdAttrGroup', 'trade');

/**
 * BaseTrdAttrGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $trd_attr_id
 * @property integer $trd_group_id
 * @property integer $sort
 * @property TrdAttribute $TrdAttribute
 * @property TrdGroup $TrdGroup
 * 
 * @method integer      getTrdAttrId()    Returns the current record's "trd_attr_id" value
 * @method integer      getTrdGroupId()   Returns the current record's "trd_group_id" value
 * @method integer      getSort()         Returns the current record's "sort" value
 * @method TrdAttribute getTrdAttribute() Returns the current record's "TrdAttribute" value
 * @method TrdGroup     getTrdGroup()     Returns the current record's "TrdGroup" value
 * @method TrdAttrGroup setTrdAttrId()    Sets the current record's "trd_attr_id" value
 * @method TrdAttrGroup setTrdGroupId()   Sets the current record's "trd_group_id" value
 * @method TrdAttrGroup setSort()         Sets the current record's "sort" value
 * @method TrdAttrGroup setTrdAttribute() Sets the current record's "TrdAttribute" value
 * @method TrdAttrGroup setTrdGroup()     Sets the current record's "TrdGroup" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdAttrGroup extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_attr_group');
        $this->hasColumn('trd_attr_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => 8,
             ));
        $this->hasColumn('trd_group_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => 8,
             ));
        $this->hasColumn('sort', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));


        $this->index('trd_attr_id', array(
             'fields' => 
             array(
              0 => 'trd_attr_id',
             ),
             ));
        $this->index('trd_group_id', array(
             'fields' => 
             array(
              0 => 'trd_group_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrdAttribute', array(
             'local' => 'trd_attr_id',
             'foreign' => 'id'));

        $this->hasOne('TrdGroup', array(
             'local' => 'trd_group_id',
             'foreign' => 'id'));
    }
}