<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('trdShaiwuProduct', 'trade');

/**
 * BasetrdShaiwuProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $intro
 * @property integer $author_id
 * @property string $author_name
 * @property integer $is_star
 * @property integer $type
 * @property integer $root_id
 * @property integer $children_id
 * @property integer $is_hot
 * @property integer $brand_id
 * @property string $model
 * @property integer $gold
 * @property string $tag_ids
 * @property integer $support
 * @property integer $agaist
 * @property integer $comment_count
 * @property string $front_pic
 * @property integer $status
 * @property string $status_reason
 * @property integer $hits
 * @property integer $activity_id
 * @property datetime $publish_time
 * @property string $source
 * @property double $rank
 * @property string $img_attr
 * @property trdShaiwuProductContent $Content
 * 
 * @method integer                 getId()            Returns the current record's "id" value
 * @method string                  getTitle()         Returns the current record's "title" value
 * @method string                  getIntro()         Returns the current record's "intro" value
 * @method integer                 getAuthorId()      Returns the current record's "author_id" value
 * @method string                  getAuthorName()    Returns the current record's "author_name" value
 * @method integer                 getIsStar()        Returns the current record's "is_star" value
 * @method integer                 getType()          Returns the current record's "type" value
 * @method integer                 getRootId()        Returns the current record's "root_id" value
 * @method integer                 getChildrenId()    Returns the current record's "children_id" value
 * @method integer                 getIsHot()         Returns the current record's "is_hot" value
 * @method integer                 getBrandId()       Returns the current record's "brand_id" value
 * @method string                  getModel()         Returns the current record's "model" value
 * @method integer                 getGold()          Returns the current record's "gold" value
 * @method string                  getTagIds()        Returns the current record's "tag_ids" value
 * @method integer                 getSupport()       Returns the current record's "support" value
 * @method integer                 getAgaist()        Returns the current record's "agaist" value
 * @method integer                 getCommentCount()  Returns the current record's "comment_count" value
 * @method string                  getFrontPic()      Returns the current record's "front_pic" value
 * @method integer                 getStatus()        Returns the current record's "status" value
 * @method string                  getStatusReason()  Returns the current record's "status_reason" value
 * @method integer                 getHits()          Returns the current record's "hits" value
 * @method integer                 getActivityId()    Returns the current record's "activity_id" value
 * @method datetime                getPublishTime()   Returns the current record's "publish_time" value
 * @method string                  getSource()        Returns the current record's "source" value
 * @method double                  getRank()          Returns the current record's "rank" value
 * @method string                  getImgAttr()       Returns the current record's "img_attr" value
 * @method trdShaiwuProductContent getContent()       Returns the current record's "Content" value
 * @method trdShaiwuProduct        setId()            Sets the current record's "id" value
 * @method trdShaiwuProduct        setTitle()         Sets the current record's "title" value
 * @method trdShaiwuProduct        setIntro()         Sets the current record's "intro" value
 * @method trdShaiwuProduct        setAuthorId()      Sets the current record's "author_id" value
 * @method trdShaiwuProduct        setAuthorName()    Sets the current record's "author_name" value
 * @method trdShaiwuProduct        setIsStar()        Sets the current record's "is_star" value
 * @method trdShaiwuProduct        setType()          Sets the current record's "type" value
 * @method trdShaiwuProduct        setRootId()        Sets the current record's "root_id" value
 * @method trdShaiwuProduct        setChildrenId()    Sets the current record's "children_id" value
 * @method trdShaiwuProduct        setIsHot()         Sets the current record's "is_hot" value
 * @method trdShaiwuProduct        setBrandId()       Sets the current record's "brand_id" value
 * @method trdShaiwuProduct        setModel()         Sets the current record's "model" value
 * @method trdShaiwuProduct        setGold()          Sets the current record's "gold" value
 * @method trdShaiwuProduct        setTagIds()        Sets the current record's "tag_ids" value
 * @method trdShaiwuProduct        setSupport()       Sets the current record's "support" value
 * @method trdShaiwuProduct        setAgaist()        Sets the current record's "agaist" value
 * @method trdShaiwuProduct        setCommentCount()  Sets the current record's "comment_count" value
 * @method trdShaiwuProduct        setFrontPic()      Sets the current record's "front_pic" value
 * @method trdShaiwuProduct        setStatus()        Sets the current record's "status" value
 * @method trdShaiwuProduct        setStatusReason()  Sets the current record's "status_reason" value
 * @method trdShaiwuProduct        setHits()          Sets the current record's "hits" value
 * @method trdShaiwuProduct        setActivityId()    Sets the current record's "activity_id" value
 * @method trdShaiwuProduct        setPublishTime()   Sets the current record's "publish_time" value
 * @method trdShaiwuProduct        setSource()        Sets the current record's "source" value
 * @method trdShaiwuProduct        setRank()          Sets the current record's "rank" value
 * @method trdShaiwuProduct        setImgAttr()       Sets the current record's "img_attr" value
 * @method trdShaiwuProduct        setContent()       Sets the current record's "Content" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetrdShaiwuProduct extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_shaiwu_product');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('intro', 'string', 350, array(
             'type' => 'string',
             'length' => 350,
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('author_name', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('is_star', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('type', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 3,
             ));
        $this->hasColumn('root_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('children_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('is_hot', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('brand_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 11,
             ));
        $this->hasColumn('model', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('gold', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 5,
             ));
        $this->hasColumn('tag_ids', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('support', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 5,
             ));
        $this->hasColumn('agaist', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 5,
             ));
        $this->hasColumn('comment_count', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('front_pic', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('status_reason', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('hits', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('publish_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('source', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('rank', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('img_attr', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));


        $this->index('status_publish_time', array(
             'fields' => 
             array(
              0 => 'status',
              1 => 'publish_time',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('trdShaiwuProductContent as Content', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}