<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllTrainingprogram', 'kaluliCMS');

/**
 * BaseKllTrainingprogram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $author
 * @property string $cover
 * @property string $articles
 * @property tinyint $order
 * @property int $h_id
 * @property int $public_time
 * @property tinyint $category
 * @property string $abstract
 * @property text $content
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method string             getTitle()       Returns the current record's "title" value
 * @method string             getAuthor()      Returns the current record's "author" value
 * @method string             getCover()       Returns the current record's "cover" value
 * @method string             getArticles()    Returns the current record's "articles" value
 * @method tinyint            getOrder()       Returns the current record's "order" value
 * @method int                getHId()         Returns the current record's "h_id" value
 * @method int                getPublicTime()  Returns the current record's "public_time" value
 * @method tinyint            getCategory()    Returns the current record's "category" value
 * @method string             getAbstract()    Returns the current record's "abstract" value
 * @method text               getContent()     Returns the current record's "content" value
 * @method KllTrainingprogram setId()          Sets the current record's "id" value
 * @method KllTrainingprogram setTitle()       Sets the current record's "title" value
 * @method KllTrainingprogram setAuthor()      Sets the current record's "author" value
 * @method KllTrainingprogram setCover()       Sets the current record's "cover" value
 * @method KllTrainingprogram setArticles()    Sets the current record's "articles" value
 * @method KllTrainingprogram setOrder()       Sets the current record's "order" value
 * @method KllTrainingprogram setHId()         Sets the current record's "h_id" value
 * @method KllTrainingprogram setPublicTime()  Sets the current record's "public_time" value
 * @method KllTrainingprogram setCategory()    Sets the current record's "category" value
 * @method KllTrainingprogram setAbstract()    Sets the current record's "abstract" value
 * @method KllTrainingprogram setContent()     Sets the current record's "content" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllTrainingprogram extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_trainingprogram');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'unsigned' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'unsigned' => true,
             'length' => 255,
             ));
        $this->hasColumn('cover', 'string', 255, array(
             'type' => 'string',
             'unsigned' => true,
             'length' => 255,
             ));
        $this->hasColumn('articles', 'string', 255, array(
             'type' => 'string',
             'unsigned' => true,
             'length' => 255,
             ));
        $this->hasColumn('order', 'tinyint', 3, array(
             'type' => 'tinyint',
             'length' => 3,
             ));
        $this->hasColumn('h_id', 'int', 10, array(
             'type' => 'int',
             'length' => 10,
             ));
        $this->hasColumn('public_time', 'int', 10, array(
             'type' => 'int',
             'length' => 10,
             ));
        $this->hasColumn('category', 'tinyint', 3, array(
             'type' => 'tinyint',
             'length' => 3,
             ));
        $this->hasColumn('abstract', 'string', 255, array(
             'type' => 'string',
             'unsigned' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}