<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KaluliArticleAttr', 'kaluli');

/**
 * BaseKaluliArticleAttr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $article_id
 * @property string $content
 * 
 * @method integer           getId()         Returns the current record's "id" value
 * @method integer           getArticleId()  Returns the current record's "article_id" value
 * @method string            getContent()    Returns the current record's "content" value
 * @method KaluliArticleAttr setId()         Sets the current record's "id" value
 * @method KaluliArticleAttr setArticleId()  Sets the current record's "article_id" value
 * @method KaluliArticleAttr setContent()    Sets the current record's "content" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKaluliArticleAttr extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_article_attr');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('content', 'string', 15000, array(
             'type' => 'string',
             'length' => 15000,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}