<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdFindStore', 'trade');

/**
 * BaseTrdFindStore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $sort
 * @property boolean $is_display
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method string       getName()       Returns the current record's "name" value
 * @method integer      getSort()       Returns the current record's "sort" value
 * @method boolean      getIsDisplay()  Returns the current record's "is_display" value
 * @method TrdFindStore setId()         Sets the current record's "id" value
 * @method TrdFindStore setName()       Sets the current record's "name" value
 * @method TrdFindStore setSort()       Sets the current record's "sort" value
 * @method TrdFindStore setIsDisplay()  Sets the current record's "is_display" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdFindStore extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_find_store');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('sort', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('is_display', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}