<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllBBProcess', 'kaluliBB');

/**
 * BaseKllBBProcess
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $id
 * @property varchar $order_number
 * @property text $content
 * @property tinyint $sequence
 * @property tinyint $status
 * @property integer $update_time
 * @property integer $create_time
 * 
 * @method int          getId()           Returns the current record's "id" value
 * @method varchar      getOrderNumber()  Returns the current record's "order_number" value
 * @method text         getContent()      Returns the current record's "content" value
 * @method tinyint      getSequence()     Returns the current record's "sequence" value
 * @method tinyint      getStatus()       Returns the current record's "status" value
 * @method integer      getUpdateTime()   Returns the current record's "update_time" value
 * @method integer      getCreateTime()   Returns the current record's "create_time" value
 * @method KllBBProcess setId()           Sets the current record's "id" value
 * @method KllBBProcess setOrderNumber()  Sets the current record's "order_number" value
 * @method KllBBProcess setContent()      Sets the current record's "content" value
 * @method KllBBProcess setSequence()     Sets the current record's "sequence" value
 * @method KllBBProcess setStatus()       Sets the current record's "status" value
 * @method KllBBProcess setUpdateTime()   Sets the current record's "update_time" value
 * @method KllBBProcess setCreateTime()   Sets the current record's "create_time" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllBBProcess extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_bb_process');
        $this->hasColumn('id', 'int', 10, array(
             'type' => 'int',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('order_number', 'varchar', 255, array(
             'type' => 'varchar',
             'unsigned' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('sequence', 'tinyint', 2, array(
             'type' => 'tinyint',
             'length' => 2,
             ));
        $this->hasColumn('status', 'tinyint', 2, array(
             'type' => 'tinyint',
             'length' => 2,
             ));
        $this->hasColumn('update_time', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 11,
             ));
        $this->hasColumn('create_time', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}