<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdNewsDatetime', 'trade');

/**
 * BaseTrdNewsDatetime
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $newsid
 * @property timestamp $publish_date
 * @property timestamp $update_date
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method integer         getNewsid()       Returns the current record's "newsid" value
 * @method timestamp       getPublishDate()  Returns the current record's "publish_date" value
 * @method timestamp       getUpdateDate()   Returns the current record's "update_date" value
 * @method TrdNewsDatetime setId()           Sets the current record's "id" value
 * @method TrdNewsDatetime setNewsid()       Sets the current record's "newsid" value
 * @method TrdNewsDatetime setPublishDate()  Sets the current record's "publish_date" value
 * @method TrdNewsDatetime setUpdateDate()   Sets the current record's "update_date" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdNewsDatetime extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_news_datetime');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('newsid', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('publish_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('update_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}