<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllKolAccount', 'kaluli');

/**
 * BaseKllKolAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kol_id
 * @property float $account
 * @property tinyint $type
 * 
 * @method integer       getKolId()   Returns the current record's "kol_id" value
 * @method float         getAccount() Returns the current record's "account" value
 * @method tinyint       getType()    Returns the current record's "type" value
 * @method KllKolAccount setKolId()   Sets the current record's "kol_id" value
 * @method KllKolAccount setAccount() Sets the current record's "account" value
 * @method KllKolAccount setType()    Sets the current record's "type" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllKolAccount extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_kol_account');
        $this->hasColumn('kol_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             ));
        $this->hasColumn('account', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('type', 'tinyint', null, array(
             'type' => 'tinyint',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}