<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdDaigouCommentTags', 'trade');

/**
 * BaseTrdDaigouCommentTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $daigou_comment_id
 * @property integer $tag_id
 * @property TrdDaigouComment $DaigouComment
 * @property TrdTags $Tag
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method integer              getDaigouCommentId()   Returns the current record's "daigou_comment_id" value
 * @method integer              getTagId()             Returns the current record's "tag_id" value
 * @method TrdDaigouComment     getDaigouComment()     Returns the current record's "DaigouComment" value
 * @method TrdTags              getTag()               Returns the current record's "Tag" value
 * @method TrdDaigouCommentTags setId()                Sets the current record's "id" value
 * @method TrdDaigouCommentTags setDaigouCommentId()   Sets the current record's "daigou_comment_id" value
 * @method TrdDaigouCommentTags setTagId()             Sets the current record's "tag_id" value
 * @method TrdDaigouCommentTags setDaigouComment()     Sets the current record's "DaigouComment" value
 * @method TrdDaigouCommentTags setTag()               Sets the current record's "Tag" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdDaigouCommentTags extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_daigou_comment_tags');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('daigou_comment_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrdDaigouComment as DaigouComment', array(
             'local' => 'daigou_comment_id',
             'foreign' => 'id'));

        $this->hasOne('TrdTags as Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id'));
    }
}