<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdJDUrlJump', 'trade');

/**
 * BaseTrdJDUrlJump
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $encrypt_url
 * @property string $url
 * @property string $jump_url
 * @property datetime $addtime
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method string       getEncryptUrl()  Returns the current record's "encrypt_url" value
 * @method string       getUrl()         Returns the current record's "url" value
 * @method string       getJumpUrl()     Returns the current record's "jump_url" value
 * @method datetime     getAddtime()     Returns the current record's "addtime" value
 * @method TrdJDUrlJump setId()          Sets the current record's "id" value
 * @method TrdJDUrlJump setEncryptUrl()  Sets the current record's "encrypt_url" value
 * @method TrdJDUrlJump setUrl()         Sets the current record's "url" value
 * @method TrdJDUrlJump setJumpUrl()     Sets the current record's "jump_url" value
 * @method TrdJDUrlJump setAddtime()     Sets the current record's "addtime" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdJDUrlJump extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_jd_url_jump');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('encrypt_url', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('url', 'string', 1000, array(
             'type' => 'string',
             'default' => '',
             'length' => 1000,
             ));
        $this->hasColumn('jump_url', 'string', 1000, array(
             'type' => 'string',
             'default' => '',
             'length' => 1000,
             ));
        $this->hasColumn('addtime', 'datetime', null, array(
             'type' => 'datetime',
             ));


        $this->index('encrypt_url', array(
             'fields' => 
             array(
              0 => 'encrypt_url',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}