<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllOrderSynApi', 'kaluli');

/**
 * BaseKllOrderSynApi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $zt
 * @property string $order_number
 * @property integer $send_gj
 * @property timestamp $send_gj_date
 * @property integer $send_hg
 * @property timestamp $send_hg_date
 * @property integer $send_zz
 * @property timestamp $send_zz_date
 * @property timestamp $syn_date
 * @property string $logisticJSON
 * @property string $logisticStepInfoJSON
 * @property integer $send_alipay
 * @property timestamp $send_alipay_date
 * 
 * @method integer        getId()                   Returns the current record's "id" value
 * @method integer        getZt()                   Returns the current record's "zt" value
 * @method string         getOrderNumber()          Returns the current record's "order_number" value
 * @method integer        getSendGj()               Returns the current record's "send_gj" value
 * @method timestamp      getSendGjDate()           Returns the current record's "send_gj_date" value
 * @method integer        getSendHg()               Returns the current record's "send_hg" value
 * @method timestamp      getSendHgDate()           Returns the current record's "send_hg_date" value
 * @method integer        getSendZz()               Returns the current record's "send_zz" value
 * @method timestamp      getSendZzDate()           Returns the current record's "send_zz_date" value
 * @method timestamp      getSynDate()              Returns the current record's "syn_date" value
 * @method string         getLogisticJSON()         Returns the current record's "logisticJSON" value
 * @method string         getLogisticStepInfoJSON() Returns the current record's "logisticStepInfoJSON" value
 * @method integer        getSendAlipay()           Returns the current record's "send_alipay" value
 * @method timestamp      getSendAlipayDate()       Returns the current record's "send_alipay_date" value
 * @method KllOrderSynApi setId()                   Sets the current record's "id" value
 * @method KllOrderSynApi setZt()                   Sets the current record's "zt" value
 * @method KllOrderSynApi setOrderNumber()          Sets the current record's "order_number" value
 * @method KllOrderSynApi setSendGj()               Sets the current record's "send_gj" value
 * @method KllOrderSynApi setSendGjDate()           Sets the current record's "send_gj_date" value
 * @method KllOrderSynApi setSendHg()               Sets the current record's "send_hg" value
 * @method KllOrderSynApi setSendHgDate()           Sets the current record's "send_hg_date" value
 * @method KllOrderSynApi setSendZz()               Sets the current record's "send_zz" value
 * @method KllOrderSynApi setSendZzDate()           Sets the current record's "send_zz_date" value
 * @method KllOrderSynApi setSynDate()              Sets the current record's "syn_date" value
 * @method KllOrderSynApi setLogisticJSON()         Sets the current record's "logisticJSON" value
 * @method KllOrderSynApi setLogisticStepInfoJSON() Sets the current record's "logisticStepInfoJSON" value
 * @method KllOrderSynApi setSendAlipay()           Sets the current record's "send_alipay" value
 * @method KllOrderSynApi setSendAlipayDate()       Sets the current record's "send_alipay_date" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllOrderSynApi extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_order_syn_api');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('zt', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('order_number', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('send_gj', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('send_gj_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('send_hg', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('send_hg_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('send_zz', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('send_zz_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('syn_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('logisticJSON', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('logisticStepInfoJSON', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('send_alipay', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 11,
             ));
        $this->hasColumn('send_alipay_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}