<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllXbuy', 'kaluli');

/**
 * BaseKllXbuy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $detail_url
 * @property integer $status
 * @property datetime $start_time
 * @property datetime $end_time
 * @property timestamp $ct_time
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method string    getDetailUrl()   Returns the current record's "detail_url" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method datetime  getStartTime()   Returns the current record's "start_time" value
 * @method datetime  getEndTime()     Returns the current record's "end_time" value
 * @method timestamp getCtTime()      Returns the current record's "ct_time" value
 * @method KllXbuy   setId()          Sets the current record's "id" value
 * @method KllXbuy   setTitle()       Sets the current record's "title" value
 * @method KllXbuy   setDescription() Sets the current record's "description" value
 * @method KllXbuy   setDetailUrl()   Sets the current record's "detail_url" value
 * @method KllXbuy   setStatus()      Sets the current record's "status" value
 * @method KllXbuy   setStartTime()   Sets the current record's "start_time" value
 * @method KllXbuy   setEndTime()     Sets the current record's "end_time" value
 * @method KllXbuy   setCtTime()      Sets the current record's "ct_time" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllXbuy extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_xbuy');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('detail_url', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('start_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('end_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('ct_time', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}