<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KaluliOrderHistory', 'kaluli');

/**
 * BaseKaluliOrderHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $order_number
 * @property integer $hupu_uid
 * @property string $hupu_username
 * @property integer $type
 * @property string $explanation
 * @property integer $grant_uid
 * @property string $grant_username
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getOrderNumber()    Returns the current record's "order_number" value
 * @method integer            getHupuUid()        Returns the current record's "hupu_uid" value
 * @method string             getHupuUsername()   Returns the current record's "hupu_username" value
 * @method integer            getType()           Returns the current record's "type" value
 * @method string             getExplanation()    Returns the current record's "explanation" value
 * @method integer            getGrantUid()       Returns the current record's "grant_uid" value
 * @method string             getGrantUsername()  Returns the current record's "grant_username" value
 * @method KaluliOrderHistory setId()             Sets the current record's "id" value
 * @method KaluliOrderHistory setOrderNumber()    Sets the current record's "order_number" value
 * @method KaluliOrderHistory setHupuUid()        Sets the current record's "hupu_uid" value
 * @method KaluliOrderHistory setHupuUsername()   Sets the current record's "hupu_username" value
 * @method KaluliOrderHistory setType()           Sets the current record's "type" value
 * @method KaluliOrderHistory setExplanation()    Sets the current record's "explanation" value
 * @method KaluliOrderHistory setGrantUid()       Sets the current record's "grant_uid" value
 * @method KaluliOrderHistory setGrantUsername()  Sets the current record's "grant_username" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKaluliOrderHistory extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_order_history');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('order_number', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('hupu_uid', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('hupu_username', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('explanation', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('grant_uid', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('grant_username', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));


        $this->index('order_number', array(
             'fields' => 
             array(
              0 => 'order_number',
             ),
             ));
        $this->index('hupu_uid', array(
             'fields' => 
             array(
              0 => 'hupu_uid',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}