<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllCpsLink', 'kaluliCPS');

/**
 * BaseKllCpsLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $title
 * @property string $channel
 * @property string $link
 * @property integer $uid
 * @property integer $cps_user_id
 * @property string $cps_user_name
 * @property integer $item_id
 * @property integer $status
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method string     getCode()          Returns the current record's "code" value
 * @method string     getTitle()         Returns the current record's "title" value
 * @method string     getChannel()       Returns the current record's "channel" value
 * @method string     getLink()          Returns the current record's "link" value
 * @method integer    getUid()           Returns the current record's "uid" value
 * @method integer    getCpsUserId()     Returns the current record's "cps_user_id" value
 * @method string     getCpsUserName()   Returns the current record's "cps_user_name" value
 * @method integer    getItemId()        Returns the current record's "item_id" value
 * @method integer    getStatus()        Returns the current record's "status" value
 * @method KllCpsLink setId()            Sets the current record's "id" value
 * @method KllCpsLink setCode()          Sets the current record's "code" value
 * @method KllCpsLink setTitle()         Sets the current record's "title" value
 * @method KllCpsLink setChannel()       Sets the current record's "channel" value
 * @method KllCpsLink setLink()          Sets the current record's "link" value
 * @method KllCpsLink setUid()           Sets the current record's "uid" value
 * @method KllCpsLink setCpsUserId()     Sets the current record's "cps_user_id" value
 * @method KllCpsLink setCpsUserName()   Sets the current record's "cps_user_name" value
 * @method KllCpsLink setItemId()        Sets the current record's "item_id" value
 * @method KllCpsLink setStatus()        Sets the current record's "status" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllCpsLink extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_cps_link');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('code', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('channel', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('uid', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('cps_user_id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('cps_user_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('item_id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));


        $this->index('code_idx', array(
             'fields' => 
             array(
              0 => 'code',
             ),
             'type' => 'unique',
             ));
        $this->index('uid', array(
             'fields' => 
             array(
              0 => 'uid',
             ),
             ));
        $this->index('item_id', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}