<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KaluliRefundApply', 'kaluli');

/**
 * BaseKaluliRefundApply
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $order_number
 * @property integer $order_id
 * @property float $refund
 * @property string $refund_remark
 * @property string $check_remark
 * @property integer $express_type
 * @property string $express_number
 * @property string $pic_attr
 * @property integer $type
 * @property integer $status
 * @property integer $grant_uid
 * @property string $grant_username
 * 
 * @method integer           getId()             Returns the current record's "id" value
 * @method integer           getOrderNumber()    Returns the current record's "order_number" value
 * @method integer           getOrderId()        Returns the current record's "order_id" value
 * @method float             getRefund()         Returns the current record's "refund" value
 * @method string            getRefundRemark()   Returns the current record's "refund_remark" value
 * @method string            getCheckRemark()    Returns the current record's "check_remark" value
 * @method integer           getExpressType()    Returns the current record's "express_type" value
 * @method string            getExpressNumber()  Returns the current record's "express_number" value
 * @method string            getPicAttr()        Returns the current record's "pic_attr" value
 * @method integer           getType()           Returns the current record's "type" value
 * @method integer           getStatus()         Returns the current record's "status" value
 * @method integer           getGrantUid()       Returns the current record's "grant_uid" value
 * @method string            getGrantUsername()  Returns the current record's "grant_username" value
 * @method KaluliRefundApply setId()             Sets the current record's "id" value
 * @method KaluliRefundApply setOrderNumber()    Sets the current record's "order_number" value
 * @method KaluliRefundApply setOrderId()        Sets the current record's "order_id" value
 * @method KaluliRefundApply setRefund()         Sets the current record's "refund" value
 * @method KaluliRefundApply setRefundRemark()   Sets the current record's "refund_remark" value
 * @method KaluliRefundApply setCheckRemark()    Sets the current record's "check_remark" value
 * @method KaluliRefundApply setExpressType()    Sets the current record's "express_type" value
 * @method KaluliRefundApply setExpressNumber()  Sets the current record's "express_number" value
 * @method KaluliRefundApply setPicAttr()        Sets the current record's "pic_attr" value
 * @method KaluliRefundApply setType()           Sets the current record's "type" value
 * @method KaluliRefundApply setStatus()         Sets the current record's "status" value
 * @method KaluliRefundApply setGrantUid()       Sets the current record's "grant_uid" value
 * @method KaluliRefundApply setGrantUsername()  Sets the current record's "grant_username" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKaluliRefundApply extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_refund_apply');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('order_number', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('order_id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('refund', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('refund_remark', 'string', 300, array(
             'type' => 'string',
             'length' => 300,
             ));
        $this->hasColumn('check_remark', 'string', 300, array(
             'type' => 'string',
             'length' => 300,
             ));
        $this->hasColumn('express_type', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('express_number', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('pic_attr', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('grant_uid', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('grant_username', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));


        $this->index('order_number', array(
             'fields' => 
             array(
              0 => 'order_number',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}