<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdUserActivityReceive', 'trade');

/**
 * BaseTrdUserActivityReceive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $username
 * @property integer $activity_id
 * 
 * @method integer                getId()          Returns the current record's "id" value
 * @method integer                getUserId()      Returns the current record's "user_id" value
 * @method string                 getUsername()    Returns the current record's "username" value
 * @method integer                getActivityId()  Returns the current record's "activity_id" value
 * @method TrdUserActivityReceive setId()          Sets the current record's "id" value
 * @method TrdUserActivityReceive setUserId()      Sets the current record's "user_id" value
 * @method TrdUserActivityReceive setUsername()    Sets the current record's "username" value
 * @method TrdUserActivityReceive setActivityId()  Sets the current record's "activity_id" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdUserActivityReceive extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_user_activity_receive');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('username', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('unite_idx', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'activity_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}