<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllWarehousesTax', 'kaluli');

/**
 * BaseKllWarehousesTax
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $warehouse_id
 * @property integer $tax_start
 * @property float $tax_rate
 * @property string $tax_note
 * @property text $tax_rule
 * @property int $status
 * 
 * @method integer          getId()           Returns the current record's "id" value
 * @method integer          getWarehouseId()  Returns the current record's "warehouse_id" value
 * @method integer          getTaxStart()     Returns the current record's "tax_start" value
 * @method float            getTaxRate()      Returns the current record's "tax_rate" value
 * @method string           getTaxNote()      Returns the current record's "tax_note" value
 * @method text             getTaxRule()      Returns the current record's "tax_rule" value
 * @method int              getStatus()       Returns the current record's "status" value
 * @method KllWarehousesTax setId()           Sets the current record's "id" value
 * @method KllWarehousesTax setWarehouseId()  Sets the current record's "warehouse_id" value
 * @method KllWarehousesTax setTaxStart()     Sets the current record's "tax_start" value
 * @method KllWarehousesTax setTaxRate()      Sets the current record's "tax_rate" value
 * @method KllWarehousesTax setTaxNote()      Sets the current record's "tax_note" value
 * @method KllWarehousesTax setTaxRule()      Sets the current record's "tax_rule" value
 * @method KllWarehousesTax setStatus()       Sets the current record's "status" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllWarehousesTax extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_warehouses_tax');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('warehouse_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('tax_start', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('tax_rate', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('tax_note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tax_rule', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('status', 'int', 2, array(
             'type' => 'int',
             'length' => 2,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}