<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdGrouponAd', 'trade');

/**
 * BaseTrdGrouponAd
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $group_id
 * @property string $title
 * @property integer $order_id
 * @property integer $stime
 * @property integer $etime
 * @property integer $pay_type
 * @property integer $pay_date
 * @property integer $is_cancel
 * @property string $reason
 * @property integer $status
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method integer      getGroupId()   Returns the current record's "group_id" value
 * @method string       getTitle()     Returns the current record's "title" value
 * @method integer      getOrderId()   Returns the current record's "order_id" value
 * @method integer      getStime()     Returns the current record's "stime" value
 * @method integer      getEtime()     Returns the current record's "etime" value
 * @method integer      getPayType()   Returns the current record's "pay_type" value
 * @method integer      getPayDate()   Returns the current record's "pay_date" value
 * @method integer      getIsCancel()  Returns the current record's "is_cancel" value
 * @method string       getReason()    Returns the current record's "reason" value
 * @method integer      getStatus()    Returns the current record's "status" value
 * @method TrdGrouponAd setId()        Sets the current record's "id" value
 * @method TrdGrouponAd setGroupId()   Sets the current record's "group_id" value
 * @method TrdGrouponAd setTitle()     Sets the current record's "title" value
 * @method TrdGrouponAd setOrderId()   Sets the current record's "order_id" value
 * @method TrdGrouponAd setStime()     Sets the current record's "stime" value
 * @method TrdGrouponAd setEtime()     Sets the current record's "etime" value
 * @method TrdGrouponAd setPayType()   Sets the current record's "pay_type" value
 * @method TrdGrouponAd setPayDate()   Sets the current record's "pay_date" value
 * @method TrdGrouponAd setIsCancel()  Sets the current record's "is_cancel" value
 * @method TrdGrouponAd setReason()    Sets the current record's "reason" value
 * @method TrdGrouponAd setStatus()    Sets the current record's "status" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdGrouponAd extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_groupon_ad');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('order_id', 'integer', 64, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 64,
             ));
        $this->hasColumn('stime', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('etime', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('pay_type', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('pay_date', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('is_cancel', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('reason', 'string', 40, array(
             'type' => 'string',
             'unsigned' => true,
             'length' => 40,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}