<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllItemTradelog', 'kaluli');

/**
 * BaseKllItemTradelog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property string $username
 * @property string $attr
 * @property integer $order_id
 * @property integer $num
 * @property integer $created_time
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method integer         getProductId()    Returns the current record's "product_id" value
 * @method string          getUsername()     Returns the current record's "username" value
 * @method string          getAttr()         Returns the current record's "attr" value
 * @method integer         getOrderId()      Returns the current record's "order_id" value
 * @method integer         getNum()          Returns the current record's "num" value
 * @method integer         getCreatedTime()  Returns the current record's "created_time" value
 * @method KllItemTradelog setId()           Sets the current record's "id" value
 * @method KllItemTradelog setProductId()    Sets the current record's "product_id" value
 * @method KllItemTradelog setUsername()     Sets the current record's "username" value
 * @method KllItemTradelog setAttr()         Sets the current record's "attr" value
 * @method KllItemTradelog setOrderId()      Sets the current record's "order_id" value
 * @method KllItemTradelog setNum()          Sets the current record's "num" value
 * @method KllItemTradelog setCreatedTime()  Sets the current record's "created_time" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllItemTradelog extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_item_tradelog');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('username', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('attr', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('num', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('created_time', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));


        $this->index('product_id_order_idx', array(
             'fields' => 
             array(
              0 => 'product_id',
              1 => 'order_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}