<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdShopInfo', 'trade');

/**
 * BaseTrdShopInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $owner_name
 * @property integer $shop_category_id
 * @property integer $shop_user_id
 * @property string $shop_info
 * @property string $memo
 * @property string $logo
 * @property string $link
 * @property string $business
 * @property string $location
 * @property string $level
 * @property string $good
 * @property integer $hupu_uid
 * @property string $discount
 * @property string $charge
 * @property integer $status
 * @property integer $position
 * @property integer $verify_status
 * @property integer $collect_count
 * @property TrdShopCategory $TrdShopCategory
 * 
 * @method integer         getId()               Returns the current record's "id" value
 * @method string          getName()             Returns the current record's "name" value
 * @method string          getOwnerName()        Returns the current record's "owner_name" value
 * @method integer         getShopCategoryId()   Returns the current record's "shop_category_id" value
 * @method integer         getShopUserId()       Returns the current record's "shop_user_id" value
 * @method string          getShopInfo()         Returns the current record's "shop_info" value
 * @method string          getMemo()             Returns the current record's "memo" value
 * @method string          getLogo()             Returns the current record's "logo" value
 * @method string          getLink()             Returns the current record's "link" value
 * @method string          getBusiness()         Returns the current record's "business" value
 * @method string          getLocation()         Returns the current record's "location" value
 * @method string          getLevel()            Returns the current record's "level" value
 * @method string          getGood()             Returns the current record's "good" value
 * @method integer         getHupuUid()          Returns the current record's "hupu_uid" value
 * @method string          getDiscount()         Returns the current record's "discount" value
 * @method string          getCharge()           Returns the current record's "charge" value
 * @method integer         getStatus()           Returns the current record's "status" value
 * @method integer         getPosition()         Returns the current record's "position" value
 * @method integer         getVerifyStatus()     Returns the current record's "verify_status" value
 * @method integer         getCollectCount()     Returns the current record's "collect_count" value
 * @method TrdShopCategory getTrdShopCategory()  Returns the current record's "TrdShopCategory" value
 * @method TrdShopInfo     setId()               Sets the current record's "id" value
 * @method TrdShopInfo     setName()             Sets the current record's "name" value
 * @method TrdShopInfo     setOwnerName()        Sets the current record's "owner_name" value
 * @method TrdShopInfo     setShopCategoryId()   Sets the current record's "shop_category_id" value
 * @method TrdShopInfo     setShopUserId()       Sets the current record's "shop_user_id" value
 * @method TrdShopInfo     setShopInfo()         Sets the current record's "shop_info" value
 * @method TrdShopInfo     setMemo()             Sets the current record's "memo" value
 * @method TrdShopInfo     setLogo()             Sets the current record's "logo" value
 * @method TrdShopInfo     setLink()             Sets the current record's "link" value
 * @method TrdShopInfo     setBusiness()         Sets the current record's "business" value
 * @method TrdShopInfo     setLocation()         Sets the current record's "location" value
 * @method TrdShopInfo     setLevel()            Sets the current record's "level" value
 * @method TrdShopInfo     setGood()             Sets the current record's "good" value
 * @method TrdShopInfo     setHupuUid()          Sets the current record's "hupu_uid" value
 * @method TrdShopInfo     setDiscount()         Sets the current record's "discount" value
 * @method TrdShopInfo     setCharge()           Sets the current record's "charge" value
 * @method TrdShopInfo     setStatus()           Sets the current record's "status" value
 * @method TrdShopInfo     setPosition()         Sets the current record's "position" value
 * @method TrdShopInfo     setVerifyStatus()     Sets the current record's "verify_status" value
 * @method TrdShopInfo     setCollectCount()     Sets the current record's "collect_count" value
 * @method TrdShopInfo     setTrdShopCategory()  Sets the current record's "TrdShopCategory" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdShopInfo extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_shop_info');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('owner_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('shop_category_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('shop_user_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('shop_info', 'string', 3000, array(
             'type' => 'string',
             'length' => 3000,
             ));
        $this->hasColumn('memo', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('business', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('location', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('level', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('good', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('hupu_uid', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('discount', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('charge', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             ));
        $this->hasColumn('verify_status', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('collect_count', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrdShopCategory', array(
             'local' => 'shop_category_id',
             'foreign' => 'id'));
    }
}