<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdGoodsTagGroup', 'trade');

/**
 * BaseTrdGoodsTagGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $click_type
 * @property string $name
 * @property text $value
 * @property integer $status
 * 
 * @method integer          getId()         Returns the current record's "id" value
 * @method integer          getClickType()  Returns the current record's "click_type" value
 * @method string           getName()       Returns the current record's "name" value
 * @method text             getValue()      Returns the current record's "value" value
 * @method integer          getStatus()     Returns the current record's "status" value
 * @method TrdGoodsTagGroup setId()         Sets the current record's "id" value
 * @method TrdGoodsTagGroup setClickType()  Sets the current record's "click_type" value
 * @method TrdGoodsTagGroup setName()       Sets the current record's "name" value
 * @method TrdGoodsTagGroup setValue()      Sets the current record's "value" value
 * @method TrdGoodsTagGroup setStatus()     Sets the current record's "status" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdGoodsTagGroup extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_goods_tag_group');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('click_type', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('value', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}