<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdSpecialVanclAwardNote', 'trade');

/**
 * BaseTrdSpecialVanclAwardNote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $match_id
 * @property integer $type
 * @property integer $uid
 * @property string $username
 * @property integer $award_id
 * @property TrdSpecialVanclMatch $TrdSpecialVanclMatch
 * @property TrdSpecialVanclAward $TrdSpecialVanclAward
 * 
 * @method integer                  getId()                   Returns the current record's "id" value
 * @method integer                  getMatchId()              Returns the current record's "match_id" value
 * @method integer                  getType()                 Returns the current record's "type" value
 * @method integer                  getUid()                  Returns the current record's "uid" value
 * @method string                   getUsername()             Returns the current record's "username" value
 * @method integer                  getAwardId()              Returns the current record's "award_id" value
 * @method TrdSpecialVanclMatch     getTrdSpecialVanclMatch() Returns the current record's "TrdSpecialVanclMatch" value
 * @method TrdSpecialVanclAward     getTrdSpecialVanclAward() Returns the current record's "TrdSpecialVanclAward" value
 * @method TrdSpecialVanclAwardNote setId()                   Sets the current record's "id" value
 * @method TrdSpecialVanclAwardNote setMatchId()              Sets the current record's "match_id" value
 * @method TrdSpecialVanclAwardNote setType()                 Sets the current record's "type" value
 * @method TrdSpecialVanclAwardNote setUid()                  Sets the current record's "uid" value
 * @method TrdSpecialVanclAwardNote setUsername()             Sets the current record's "username" value
 * @method TrdSpecialVanclAwardNote setAwardId()              Sets the current record's "award_id" value
 * @method TrdSpecialVanclAwardNote setTrdSpecialVanclMatch() Sets the current record's "TrdSpecialVanclMatch" value
 * @method TrdSpecialVanclAwardNote setTrdSpecialVanclAward() Sets the current record's "TrdSpecialVanclAward" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdSpecialVanclAwardNote extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_special_vancl_award_note');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('match_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('type', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('username', 'string', 45, array(
             'type' => 'string',
             'default' => '',
             'length' => 45,
             ));
        $this->hasColumn('award_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrdSpecialVanclMatch', array(
             'local' => 'match_id',
             'foreign' => 'id'));

        $this->hasOne('TrdSpecialVanclAward', array(
             'local' => 'award_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}