<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdGoodsAddress', 'trade');

/**
 * BaseTrdGoodsAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $activity_id
 * @property integer $hupu_uid
 * @property string $hupu_username
 * @property string $name
 * @property string $tel
 * @property string $province
 * @property string $city
 * @property string $address
 * @property string $note
 * @property integer $status
 * 
 * @method integer         getId()            Returns the current record's "id" value
 * @method integer         getActivityId()    Returns the current record's "activity_id" value
 * @method integer         getHupuUid()       Returns the current record's "hupu_uid" value
 * @method string          getHupuUsername()  Returns the current record's "hupu_username" value
 * @method string          getName()          Returns the current record's "name" value
 * @method string          getTel()           Returns the current record's "tel" value
 * @method string          getProvince()      Returns the current record's "province" value
 * @method string          getCity()          Returns the current record's "city" value
 * @method string          getAddress()       Returns the current record's "address" value
 * @method string          getNote()          Returns the current record's "note" value
 * @method integer         getStatus()        Returns the current record's "status" value
 * @method TrdGoodsAddress setId()            Sets the current record's "id" value
 * @method TrdGoodsAddress setActivityId()    Sets the current record's "activity_id" value
 * @method TrdGoodsAddress setHupuUid()       Sets the current record's "hupu_uid" value
 * @method TrdGoodsAddress setHupuUsername()  Sets the current record's "hupu_username" value
 * @method TrdGoodsAddress setName()          Sets the current record's "name" value
 * @method TrdGoodsAddress setTel()           Sets the current record's "tel" value
 * @method TrdGoodsAddress setProvince()      Sets the current record's "province" value
 * @method TrdGoodsAddress setCity()          Sets the current record's "city" value
 * @method TrdGoodsAddress setAddress()       Sets the current record's "address" value
 * @method TrdGoodsAddress setNote()          Sets the current record's "note" value
 * @method TrdGoodsAddress setStatus()        Sets the current record's "status" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdGoodsAddress extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_goods_address');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('hupu_uid', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('hupu_username', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('tel', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('province', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('city', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));


        $this->index('status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}