<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllLipinkaRecordGroup', 'kaluli');

/**
 * BaseKllLipinkaRecordGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $record_id
 * @property integer $item_id
 * 
 * @method integer               getId()        Returns the current record's "id" value
 * @method integer               getRecordId()  Returns the current record's "record_id" value
 * @method integer               getItemId()    Returns the current record's "item_id" value
 * @method KllLipinkaRecordGroup setId()        Sets the current record's "id" value
 * @method KllLipinkaRecordGroup setRecordId()  Sets the current record's "record_id" value
 * @method KllLipinkaRecordGroup setItemId()    Sets the current record's "item_id" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllLipinkaRecordGroup extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_lipinka_record_group');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('record_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}