<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllCommentTagsCount', 'kaluli');

/**
 * BaseKllCommentTagsCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property integer $tag_id
 * @property integer $comment_id
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getProductId()  Returns the current record's "product_id" value
 * @method integer             getTagId()      Returns the current record's "tag_id" value
 * @method integer             getCommentId()  Returns the current record's "comment_id" value
 * @method KllCommentTagsCount setId()         Sets the current record's "id" value
 * @method KllCommentTagsCount setProductId()  Sets the current record's "product_id" value
 * @method KllCommentTagsCount setTagId()      Sets the current record's "tag_id" value
 * @method KllCommentTagsCount setCommentId()  Sets the current record's "comment_id" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllCommentTagsCount extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_comment_tags_count');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}