<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdUserRecommend', 'trade');

/**
 * BaseTrdUserRecommend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $recommend_content
 * @property integer $recommend_type
 * @property integer $recommend_id
 * @property datetime $create_time
 * @property integer $is_delete
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method integer          getUserId()            Returns the current record's "user_id" value
 * @method string           getRecommendContent()  Returns the current record's "recommend_content" value
 * @method integer          getRecommendType()     Returns the current record's "recommend_type" value
 * @method integer          getRecommendId()       Returns the current record's "recommend_id" value
 * @method datetime         getCreateTime()        Returns the current record's "create_time" value
 * @method integer          getIsDelete()          Returns the current record's "is_delete" value
 * @method TrdUserRecommend setId()                Sets the current record's "id" value
 * @method TrdUserRecommend setUserId()            Sets the current record's "user_id" value
 * @method TrdUserRecommend setRecommendContent()  Sets the current record's "recommend_content" value
 * @method TrdUserRecommend setRecommendType()     Sets the current record's "recommend_type" value
 * @method TrdUserRecommend setRecommendId()       Sets the current record's "recommend_id" value
 * @method TrdUserRecommend setCreateTime()        Sets the current record's "create_time" value
 * @method TrdUserRecommend setIsDelete()          Sets the current record's "is_delete" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdUserRecommend extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_user_recommend');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('recommend_content', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('recommend_type', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('recommend_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('create_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('is_delete', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));


        $this->index('user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('user_id_id', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'id',
             ),
             ));
        $this->index('user_recommend_type_id', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'recommend_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}