<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CpsOrder', 'tradeCPS');

/**
 * BaseCpsOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $order_number
 * @property integer $sub_order_number
 * @property integer $order_time
 * @property integer $click_time
 * @property float $orders_price
 * @property float $discount_amount
 * @property string $promotion_code
 * @property integer $is_new_custom
 * @property integer $channel
 * @property integer $status
 * @property integer $goods_id
 * @property string $title
 * @property float $goods_price
 * @property integer $goods_ta
 * @property integer $goods_cate
 * @property string $goods_cate_name
 * @property float $total_price
 * @property float $rate
 * @property float $commission
 * @property string $commission_type
 * @property integer $test
 * @property string $union_id
 * @property string $mid
 * @property string $euid
 * @property string $referer
 * @property integer $valid
 * @property integer $hupu_uid
 * 
 * @method integer  getId()               Returns the current record's "id" value
 * @method integer  getOrderNumber()      Returns the current record's "order_number" value
 * @method integer  getSubOrderNumber()   Returns the current record's "sub_order_number" value
 * @method integer  getOrderTime()        Returns the current record's "order_time" value
 * @method integer  getClickTime()        Returns the current record's "click_time" value
 * @method float    getOrdersPrice()      Returns the current record's "orders_price" value
 * @method float    getDiscountAmount()   Returns the current record's "discount_amount" value
 * @method string   getPromotionCode()    Returns the current record's "promotion_code" value
 * @method integer  getIsNewCustom()      Returns the current record's "is_new_custom" value
 * @method integer  getChannel()          Returns the current record's "channel" value
 * @method integer  getStatus()           Returns the current record's "status" value
 * @method integer  getGoodsId()          Returns the current record's "goods_id" value
 * @method string   getTitle()            Returns the current record's "title" value
 * @method float    getGoodsPrice()       Returns the current record's "goods_price" value
 * @method integer  getGoodsTa()          Returns the current record's "goods_ta" value
 * @method integer  getGoodsCate()        Returns the current record's "goods_cate" value
 * @method string   getGoodsCateName()    Returns the current record's "goods_cate_name" value
 * @method float    getTotalPrice()       Returns the current record's "total_price" value
 * @method float    getRate()             Returns the current record's "rate" value
 * @method float    getCommission()       Returns the current record's "commission" value
 * @method string   getCommissionType()   Returns the current record's "commission_type" value
 * @method integer  getTest()             Returns the current record's "test" value
 * @method string   getUnionId()          Returns the current record's "union_id" value
 * @method string   getMid()              Returns the current record's "mid" value
 * @method string   getEuid()             Returns the current record's "euid" value
 * @method string   getReferer()          Returns the current record's "referer" value
 * @method integer  getValid()            Returns the current record's "valid" value
 * @method integer  getHupuUid()          Returns the current record's "hupu_uid" value
 * @method CpsOrder setId()               Sets the current record's "id" value
 * @method CpsOrder setOrderNumber()      Sets the current record's "order_number" value
 * @method CpsOrder setSubOrderNumber()   Sets the current record's "sub_order_number" value
 * @method CpsOrder setOrderTime()        Sets the current record's "order_time" value
 * @method CpsOrder setClickTime()        Sets the current record's "click_time" value
 * @method CpsOrder setOrdersPrice()      Sets the current record's "orders_price" value
 * @method CpsOrder setDiscountAmount()   Sets the current record's "discount_amount" value
 * @method CpsOrder setPromotionCode()    Sets the current record's "promotion_code" value
 * @method CpsOrder setIsNewCustom()      Sets the current record's "is_new_custom" value
 * @method CpsOrder setChannel()          Sets the current record's "channel" value
 * @method CpsOrder setStatus()           Sets the current record's "status" value
 * @method CpsOrder setGoodsId()          Sets the current record's "goods_id" value
 * @method CpsOrder setTitle()            Sets the current record's "title" value
 * @method CpsOrder setGoodsPrice()       Sets the current record's "goods_price" value
 * @method CpsOrder setGoodsTa()          Sets the current record's "goods_ta" value
 * @method CpsOrder setGoodsCate()        Sets the current record's "goods_cate" value
 * @method CpsOrder setGoodsCateName()    Sets the current record's "goods_cate_name" value
 * @method CpsOrder setTotalPrice()       Sets the current record's "total_price" value
 * @method CpsOrder setRate()             Sets the current record's "rate" value
 * @method CpsOrder setCommission()       Sets the current record's "commission" value
 * @method CpsOrder setCommissionType()   Sets the current record's "commission_type" value
 * @method CpsOrder setTest()             Sets the current record's "test" value
 * @method CpsOrder setUnionId()          Sets the current record's "union_id" value
 * @method CpsOrder setMid()              Sets the current record's "mid" value
 * @method CpsOrder setEuid()             Sets the current record's "euid" value
 * @method CpsOrder setReferer()          Sets the current record's "referer" value
 * @method CpsOrder setValid()            Sets the current record's "valid" value
 * @method CpsOrder setHupuUid()          Sets the current record's "hupu_uid" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpsOrder extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cps_order');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('order_number', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('sub_order_number', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('order_time', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('click_time', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('orders_price', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('discount_amount', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('promotion_code', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('is_new_custom', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('channel', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('goods_id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('goods_price', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('goods_ta', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('goods_cate', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 10,
             ));
        $this->hasColumn('goods_cate_name', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('total_price', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('rate', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('commission', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('commission_type', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('test', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('union_id', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('mid', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('euid', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('referer', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('valid', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('hupu_uid', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));


        $this->index('order_number', array(
             'fields' => 
             array(
              0 => 'order_number',
             ),
             ));
        $this->index('click_time', array(
             'fields' => 
             array(
              0 => 'click_time',
             ),
             ));
        $this->index('union_id', array(
             'fields' => 
             array(
              0 => 'union_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}