<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdReferUrl', 'trade');

/**
 * BaseTrdReferUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property string $encrypt_url
 * @property integer $tp
 * @property datetime $addtime
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method string      getUrl()         Returns the current record's "url" value
 * @method string      getEncryptUrl()  Returns the current record's "encrypt_url" value
 * @method integer     getTp()          Returns the current record's "tp" value
 * @method datetime    getAddtime()     Returns the current record's "addtime" value
 * @method TrdReferUrl setId()          Sets the current record's "id" value
 * @method TrdReferUrl setUrl()         Sets the current record's "url" value
 * @method TrdReferUrl setEncryptUrl()  Sets the current record's "encrypt_url" value
 * @method TrdReferUrl setTp()          Sets the current record's "tp" value
 * @method TrdReferUrl setAddtime()     Sets the current record's "addtime" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdReferUrl extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_refer_url');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('encrypt_url', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('tp', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 1,
             ));
        $this->hasColumn('addtime', 'datetime', null, array(
             'type' => 'datetime',
             ));


        $this->index('encrypt_url', array(
             'fields' => 
             array(
              0 => 'encrypt_url',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}