<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllOrder', 'kaluliBB');

/**
 * BaseKllOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $id
 * @property varchar $order_number
 * @property varchar $child_order_number
 * @property varchar $name
 * @property varchar $description
 * @property varchar $receiver
 * @property varchar $product_code
 * @property int $product_id
 * @property int $goods_id
 * @property float $total_price
 * @property int $pay_time
 * @property tinyint $pay_status
 * @property float $price
 * @property int $number
 * @property int $update_time
 * @property integer $creat_time
 * 
 * @method int      getId()                 Returns the current record's "id" value
 * @method varchar  getOrderNumber()        Returns the current record's "order_number" value
 * @method varchar  getChildOrderNumber()   Returns the current record's "child_order_number" value
 * @method varchar  getName()               Returns the current record's "name" value
 * @method varchar  getDescription()        Returns the current record's "description" value
 * @method varchar  getReceiver()           Returns the current record's "receiver" value
 * @method varchar  getProductCode()        Returns the current record's "product_code" value
 * @method int      getProductId()          Returns the current record's "product_id" value
 * @method int      getGoodsId()            Returns the current record's "goods_id" value
 * @method float    getTotalPrice()         Returns the current record's "total_price" value
 * @method int      getPayTime()            Returns the current record's "pay_time" value
 * @method tinyint  getPayStatus()          Returns the current record's "pay_status" value
 * @method float    getPrice()              Returns the current record's "price" value
 * @method int      getNumber()             Returns the current record's "number" value
 * @method int      getUpdateTime()         Returns the current record's "update_time" value
 * @method integer  getCreatTime()          Returns the current record's "creat_time" value
 * @method KllOrder setId()                 Sets the current record's "id" value
 * @method KllOrder setOrderNumber()        Sets the current record's "order_number" value
 * @method KllOrder setChildOrderNumber()   Sets the current record's "child_order_number" value
 * @method KllOrder setName()               Sets the current record's "name" value
 * @method KllOrder setDescription()        Sets the current record's "description" value
 * @method KllOrder setReceiver()           Sets the current record's "receiver" value
 * @method KllOrder setProductCode()        Sets the current record's "product_code" value
 * @method KllOrder setProductId()          Sets the current record's "product_id" value
 * @method KllOrder setGoodsId()            Sets the current record's "goods_id" value
 * @method KllOrder setTotalPrice()         Sets the current record's "total_price" value
 * @method KllOrder setPayTime()            Sets the current record's "pay_time" value
 * @method KllOrder setPayStatus()          Sets the current record's "pay_status" value
 * @method KllOrder setPrice()              Sets the current record's "price" value
 * @method KllOrder setNumber()             Sets the current record's "number" value
 * @method KllOrder setUpdateTime()         Sets the current record's "update_time" value
 * @method KllOrder setCreatTime()          Sets the current record's "creat_time" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllOrder extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_order');
        $this->hasColumn('id', 'int', 10, array(
             'type' => 'int',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('order_number', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('child_order_number', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('description', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('receiver', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('product_code', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('product_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('goods_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('total_price', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('pay_time', 'int', 10, array(
             'type' => 'int',
             'length' => 10,
             ));
        $this->hasColumn('pay_status', 'tinyint', 5, array(
             'type' => 'tinyint',
             'length' => 5,
             ));
        $this->hasColumn('price', 'float', 8, array(
             'type' => 'float',
             'length' => 8,
             'scale' => 2,
             ));
        $this->hasColumn('number', 'int', 5, array(
             'type' => 'int',
             'length' => 5,
             ));
        $this->hasColumn('update_time', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('creat_time', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}