<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdDaigouBrand', 'trade');

/**
 * BaseTrdDaigouBrand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $root_id
 * @property integer $children_id
 * @property string $brand_attr
 * @property integer $status
 * @property datetime $created_at
 * @property datetime $updated_at
 * 
 * @method integer        getId()          Returns the current record's "id" value
 * @method integer        getRootId()      Returns the current record's "root_id" value
 * @method integer        getChildrenId()  Returns the current record's "children_id" value
 * @method string         getBrandAttr()   Returns the current record's "brand_attr" value
 * @method integer        getStatus()      Returns the current record's "status" value
 * @method datetime       getCreatedAt()   Returns the current record's "created_at" value
 * @method datetime       getUpdatedAt()   Returns the current record's "updated_at" value
 * @method TrdDaigouBrand setId()          Sets the current record's "id" value
 * @method TrdDaigouBrand setRootId()      Sets the current record's "root_id" value
 * @method TrdDaigouBrand setChildrenId()  Sets the current record's "children_id" value
 * @method TrdDaigouBrand setBrandAttr()   Sets the current record's "brand_attr" value
 * @method TrdDaigouBrand setStatus()      Sets the current record's "status" value
 * @method TrdDaigouBrand setCreatedAt()   Sets the current record's "created_at" value
 * @method TrdDaigouBrand setUpdatedAt()   Sets the current record's "updated_at" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdDaigouBrand extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_daigou_brand');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('root_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('children_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('brand_attr', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('updated_at', 'datetime', null, array(
             'type' => 'datetime',
             ));


        $this->index('children_id', array(
             'fields' => 
             array(
              0 => 'children_id',
             ),
             ));
        $this->index('root_id', array(
             'fields' => 
             array(
              0 => 'root_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}