<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TrdCollectionItems', 'trade');

/**
 * BaseTrdCollectionItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $collection_id
 * @property integer $item_all_id
 * @property TrdItemAll $TrdItemAll
 * @property TrdCollections $TrdCollections
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getCollectionId()   Returns the current record's "collection_id" value
 * @method integer            getItemAllId()      Returns the current record's "item_all_id" value
 * @method TrdItemAll         getTrdItemAll()     Returns the current record's "TrdItemAll" value
 * @method TrdCollections     getTrdCollections() Returns the current record's "TrdCollections" value
 * @method TrdCollectionItems setId()             Sets the current record's "id" value
 * @method TrdCollectionItems setCollectionId()   Sets the current record's "collection_id" value
 * @method TrdCollectionItems setItemAllId()      Sets the current record's "item_all_id" value
 * @method TrdCollectionItems setTrdItemAll()     Sets the current record's "TrdItemAll" value
 * @method TrdCollectionItems setTrdCollections() Sets the current record's "TrdCollections" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrdCollectionItems extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trd_collection_items');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('collection_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('item_all_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));


        $this->index('collection_item', array(
             'fields' => 
             array(
              0 => 'collection_id',
              1 => 'item_all_id',
             ),
             'type' => 'unique',
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrdItemAll', array(
             'local' => 'item_all_id',
             'foreign' => 'id'));

        $this->hasOne('TrdCollections', array(
             'local' => 'collection_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}