<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KllCommentTagsDetail', 'kaluli');

/**
 * BaseKllCommentTagsDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $is_hide
 * 
 * @method integer              getId()      Returns the current record's "id" value
 * @method string               getName()    Returns the current record's "name" value
 * @method boolean              getIsHide()  Returns the current record's "is_hide" value
 * @method KllCommentTagsDetail setId()      Sets the current record's "id" value
 * @method KllCommentTagsDetail setName()    Sets the current record's "name" value
 * @method KllCommentTagsDetail setIsHide()  Sets the current record's "is_hide" value
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKllCommentTagsDetail extends sfDoctrineMasterSlaveRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kll_comment_tags_detail');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('is_hide', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}