generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TrdAdminUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          trd_admin_user
    with_doctrine_route:   true
    actions_base_class:    AdminBaseAction

    config:
      actions:
        _new: { label: "添加会员" }
        _edit: { label: "编辑会员" }
        _delete: { label: "删除" }
        _save: { label: "保存" }
        actions:
          _delete:
            label: 删除
          _edit:
            label: 编辑
          _new:
            label: 添加
          _save:
            label: 保存
      fields:
        id:
          label: id
        hupu_uid:
          label: 虎扑ID
        password:
          label: 密码
        verify:
          label: 密码加盐码
        role:
          label: 用户组
        qq:
          label: qq
        created_at:
          label: 添加时间
        updated_at: { label: 最后更新时间, date_format: yyyy-dd-MM hh:mm:ss }
        username:
          label: 用户名
        channel:
          label: 渠道
        mobile:
          label: 手机号
        last_login_time: { label: 最后登录时间, date_format: yyyy-dd-MM HH:mm:ss }
        last_login_ip:
          label: 最后登录IP
        user_status:
          label: 状态
        user_status_html:
          label: 状态
        Actions:
          label: 操作
      list:
        title: 后台会员列表
        display: [id,username,qq,email,mobile,last_login_time,last_login_ip,user_status_html]
        max_per_page: 20
        sort: [id, asc]
        object_actions:
          _edit:
            label: 编辑
          _delete:
            label: 删除
      edit:
        title: 编辑用户
      new:
        title: 添加用户
      filter:
        display:
          - username
          - email
          - qq
          - mobile
      form:    ~
