<?php

/**
 * CpsOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpsOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpsOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CpsOrder');
    }
}