<?php

/**
 * KaluliTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KaluliTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KaluliTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KaluliTags');
    }

    public static function houtaGetCount()
    {
        return self::getInstance()->createQuery()->count();
    }


    public static function houtaGetList($offset=0,$limit=20)
    {
        $query = self::getInstance()->createQuery()
            ->orderBy('weight desc')
            ->offset($offset)
            ->limit($limit);
        return $query->fetchArray();
    }


    public static function getListByType()
    {
        $tmp = self::getInstance()->createQuery()
            ->fetchArray();
        if(empty($tmp)) return false;
        foreach($tmp as $tag)
        {
            $data[$tag['type']][$tag['id']] = $tag['name'];
        }
        return $data;
     }
}