<?php

/**
 * KaluliKeyValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KaluliKeyValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KaluliKeyValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KaluliKeyValue');
    }
}