<?php

/**
 * KaluliMainOrderAttrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KaluliMainOrderAttrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KaluliMainOrderAttrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KaluliMainOrderAttr');
    }



    /**
     * 获取一条数据
     * @param $order_number  订单id
     * @param bool $is_toArray  是否转成数组
     * @param bool $is_all     是否全部展示
     */
    public static function getOne($order_number,$is_toArray = false,$field = false,$is_all = true) {
        $info = self::getInstance()
            ->createQuery()
            ->select('*')
            ->andWhere('order_number = ?',$order_number)
            ->fetchOne();
        if(empty($info)) return false;
        if(!$is_toArray) return $info;
        $info = $info->toArray();
        //转换 json
        $info['address_attr'] = json_decode($info['address_attr'],true);
        if($field) {
            return $info[$field];
        } else {
            return $info;
        }
        return $info;
    }

    public static function  getAll($bind = array()) {
        $data = self::getInstance()->createQuery();
        //select
        if (!empty($bind['select'])){
            $data->select($bind['select']);
        } else {
            $data->select("*");
        }
        //leftJoin
        if (!empty($bind['leftJoin'])){
            $data->leftJoin($bind['leftJoin']);
        }
        //where 简单判断  如果复杂 建议新写函数
        if(!empty($bind['where']) && count($bind['where']) > 0) {
            foreach($bind['where'] as $k=>$v) {
                $data->addWhere($v);
            }
        }

        //whereIn 简单判断  如果复杂 建议新写函数
        if(!empty($bind['whereIn']) && count($bind['whereIn']) > 0) {
            foreach($bind['whereIn'] as $k=>$v) {
                $data->WhereIn($k,$v);
            }
        }

        //order
        if (!empty($bind['order'])){
            $data->orderBy($bind['order']);
        } else {
            $data->orderBy('id desc');
        }
        //limit
        if (!empty($bind['limit'])){
            $data->limit($bind['limit']);
        }

        if(!empty($bind['offset'])) {
            $data->offset($bind['offset']);
        }
        if(!empty($bind['groupBY'])){
            $data->groupBy($bind['groupBY']);
        }
        $data =  $data->fetchArray();
        if(!empty($bind['is_count'])) {
            $data = $data[0]['num'];
        }
        return $data;
    }
}