<?php

/**
 * KaluliRefundApply
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class KaluliRefundApply extends BaseKaluliRefundApply
{
   public static $refund_type = array(//退款说明
       0=>'发货错误',
       1=>'质量有问题',
       2=>'商品过期',
       3=>'不想要了',
       4=>'其他'
   );

    public static $domestic_express_type = array(//快递公司
        1=>'申通',
        2=>'顺丰',
        3=>'EMS',
        4=>'圆通',
        5=>'韵达',
        6=>'中通',
        7=>'天天',
        8=>'汇通',
        9=>'宅急送',
        10=>'其他',
    );

    public static $status = array(//快递公司
        0=>'待审核',
        1=>'待发货',
        2=>'待收货',
        3=>'待退款',
        4=>'退款完成',
        5=>'拒绝退货',
    );
}
