<?php

/**
 * KaluliLipinkaRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class KaluliLipinkaRecord extends BaseKaluliLipinkaRecord
{
    public static $POSTPONE_BEFORE = 1;  //预先生成
    public static $POSTPONE_DYNAMIC = 2;  //动态生成

    public static $TYPE_CARD = 1;  //生成卡密
    public static $TYPE_ACCOUNT= 2; //发到账户里面
}
