<?php

/**
 * KllAdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllAdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllAdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllAd');
    }
}