<?php

/**
 * KllBBMainOrderAttrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllBBMainOrderAttrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllBBMainOrderAttrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllBBMainOrderAttr');
    }
    
	public static function getAttrByOrderNumber($order_number){
    	$info = self::getInstance()
            ->createQuery()
            ->select('*')
            ->andWhere('order_number = ?',$order_number)
            ->fetchArray();
        if($info) return $info;
    }
}