<?php

/**
 * KllBBOrderSynApiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllBBOrderSynApiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllBBOrderSynApiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllBBOrderSynApi');
    }
    //获得订单
    public static function getByOrderNumber($order_number) {
        $data = self::getInstance()->createQuery();
        $data->select("*")
             ->where("order_number = ?",$order_number);
             
        $order = $data->fetchArray();
        
        return $order;
    }
}