<?php

/**
 * KllCouponsDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllCouponsDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllCouponsDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllCouponsDetail');
    }
}