<?php

/**
 * KllCpsLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class KllCpsLink extends BaseKllCpsLink
{

    public static $_STATUS_FINE = 1;
    public static $_STATUS_DEL = 2;

}
