<?php

/**
 * KllKolAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllKolAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllKolAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllKolAccount');
    }
}