<?php

/**
 * KllMqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllMqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllMqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllMq');
    }
    //获得对应的回执信息
    static function  getMQByChildOrderID($bind = []){
        $sql = self::getInstance()->createQuery();
        //select
        if (!empty($bind['select'])){
            $sql->select($bind['select']);
        } else {
            $sql->select("*");
        }

        //where 简单判断  如果复杂 建议新写函数
        if(!empty($bind['where']) && count($bind['where']) > 0) {
            foreach($bind['where'] as $k=>$v) {
                $sql->addWhere($v);
            }
        }
        $data =  $sql->fetchArray();
        return $data;
    }
}