<?php

/**
 * KllOrderLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllOrderLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllOrderLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllOrderLog');
    }
}