<?php

/**
 * KllTalentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllTalentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllTalentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllTalent');
    }
}