<?php

/**
 * KllWxpayReturnLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KllWxpayReturnLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KllWxpayReturnLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KllWxpayReturnLog');
    }
}