<?php

/**
 * TrdAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TrdAccount extends BaseTrdAccount
{
    public function save(Doctrine_Connection $conn = null) 
    {
        $modifiedFields = $this->getModified(true);     
        parent::save($conn);

        //同步积分到个人中心
//         $syncAskKeyArray =array('integral','gold');
//        if($this->isNew() || array_intersect($syncAskKeyArray,array_keys($modifiedFields)))
//        {        
//            $this->syncAskToSphinx();
//        }

        //更新redis中的个人信息
        $updateInfoKeyArray =array('integral','gold');
        if(array_intersect($updateInfoKeyArray,array_keys($modifiedFields)))
        {
            $serviceRequest = new tradeServiceClient();
            $serviceRequest->setMethod('user.info.update');
            $serviceRequest->setVersion('1.0');
            $serviceRequest->setUserToken(sfContext::getInstance()->getRequest()->getCookie('u'));
            $response = $serviceRequest->execute();
        }


        return $this->getId();
        
    }
    
    //发送消息到个人中心
    public function syncAskToSphinx()
    {
        hcRabbitMQPublisher::getInstance('shihuo_user')->publish(new hcAMQPMessage(array('type'=>'update','uid'=>$this->getHupuUid(),'integral'=>$this->getIntegral(),'gold'=>$this->getGold())),'shihuo_user_account');
        return true;
    }

    public function formatApp()
    {
        $data = array();
        $data['hupu_uid'] = $this->getHupuUid();
        $data['hupu_username'] = $this->getHupuUsername();
        $data['integral'] = $this->getIntegral();
        $data['gold'] = $this->getGold();
        return $data;
    }





    public function getLevel()
    {
        $integral = $this->getIntegral();
        $info = array();

        if($integral>= 0 && $integral <= 600 )
        {
            $info['level'] = 1;
            $info['name']  = "识货小弟";
            $info['percentage'] =  round(($integral - 0)/(600-0),2)*100;
        }elseif($integral> 600 && $integral <= 1000 ){
            $info['level'] = 2;
            $info['name']  = "识货贫农";
            $info['percentage'] =  round(($integral - 600)/(1000-600),2)*100;
        }elseif($integral> 1000 && $integral <= 1600 ){
            $info['level'] = 3;
            $info['name']  = "识货贫民";
            $info['percentage'] =  round(($integral - 1000)/(1600-1000),2)*100;
        }elseif($integral> 1600 && $integral <= 2400 ){
            $info['level'] = 4;
            $info['name']  = "识货小康";
            $info['percentage'] =  round(($integral - 1600)/(2400-1600),2)*100;
        }elseif($integral> 2400 && $integral <= 6000 ){
            $info['level'] = 5;
            $info['name']  = "识货少爷";
            $info['percentage'] =  round(($integral - 2400)/(6000-2400),2)*100;
        }elseif($integral> 6000 && $integral <= 8000 ){
            $info['level'] = 6;
            $info['name']  = "识货地主";
            $info['percentage'] =  round(($integral - 6000)/(8000-6000),2)*100;
        }else if($integral> 8000 && $integral <= 12000 ){
            $info['level'] = 7;
            $info['name']  = "识货财主";
            $info['percentage'] =  round(($integral - 8000)/(12000-8000),2)*100;
        }else if($integral> 12000 && $integral <= 16000 ){
            $info['level'] = 8;
            $info['name']  = "识货款爷";
            $info['percentage'] =  round(($integral - 12000)/(16000-12000),2)*100;
        }else if($integral> 16000 && $integral <= 20000 ){
            $info['level'] = 9;
            $info['name']  = "识货土豪";
            $info['percentage'] =  round(($integral - 16000)/(20000-16000),2)*100;
        }else if($integral> 20000 && $integral <= 30000 ){
            $info['level'] = 10;
            $info['name']  = "识货巨富";
            $info['percentage'] =  round(($integral - 20000)/(30000-20000),2)*100;
        }else if($integral  > 30000 ){
            $info['level'] = 10;
            $info['name']  = "识货巨富";
            $info['percentage'] =  100;
        }

        return $info;
    }

}
