<?php

/**
 * TrdActivitySetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdActivitySetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdActivitySetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdActivitySet');
    }
}