<?php

/**
 * TrdAmzProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdAmzProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdAmzProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdAmzProduct');
    }
}