<?php

/**
 * TrdBrandTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdBrandTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdBrandTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdBrand');
    }

    public function getAll() {
        return self::getInstance()->createQuery('a')
            ->select('*')
            ->orderby("is_default desc")
            ->execute();
    }

    public function getAllName() {
        $allName = array();
        $obj =  self::getInstance()->createQuery('a')
            ->setResultCacheLifeSpan(60*10)
            ->useResultCache()
            ->select('*')
            ->orderby("is_default desc")
            ->execute();
        foreach($obj as $k=>$v){
            $allName[$v->getId()] =  $v->getName();
        }

        return $allName;
    }

    public function getBrandByName($name)
    {
      return self::getInstance()->createQuery()
                                ->where('name = ?', trim($name))
                                ->fetchOne();
    }    

    public function search($name) {
        return self::getInstance()->createQuery()
            ->where('name like ?', "%" . trim($name) . "%")
            ->execute();
    }
    
    
    public function getSomeById($ids)
    {
       
        $brand_info = TrdBrandTable::getInstance()->createQuery()->whereIn('id',$ids)->execute();
        $result = array();
        foreach($brand_info as $brand)
        {
            $result[$brand->getId()] = $brand;
        }
        return $result;
    }

    static public function getBrandName($id)
    {
       if($id){
           return  self::getInstance()->createQuery()->where('id = ?', $id)->fetchOne()->getName();
       }else{
           return '';
       }
    }
}
