<?php

/**
 * TrdCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdComment');
    }

    public static function deleteMessage($id){

        $serviceRequest = new tradeServiceClient();
        $serviceRequest->setMethod('comment.comment.delete');
        $serviceRequest->setVersion('1.0');
        $serviceRequest->setApiParam('commentId', $id);
        $response = $serviceRequest->execute();

        $data = $response->getData();
        if($data['status'] == 200){
            return true;
        }else{
            return false;
        }
    }

    public static function myListQuery() {
        $query = self::getInstance()->createQuery('m')
            ->whereIn('m.status',array(0,1))
            ->orderBy('m.created_at DESC');
        return $query;
    }

    /*
    * 获取信息
    */
    public  static  function getMessage($array = array()){
        if(isset($array['limit']))
            $limit = $array['limit'];
        else
            $limit = 10;

        if(isset($array['page']))
            $num = ($array['page']-1)*$limit;
        else
            $num = 0;

        if(isset($array['order']))
            $order = $array['order'];
        else
            $order = "created_at DESC";

        $objs = self::getInstance()->createQuery('t')->where('t.status = 1')->limit($limit)->offset($num)->orderBy($order);

        if(isset($array['select'])) $objs = $objs->select($array['select']);
        if(isset($array['id']) && !empty($array['id']))$objs = $objs->andwhere("t.id  in (" .  rtrim(join(",",$array['id']),',') . ") ");
        if(isset($array['day'])) $objs = $objs->andWhere('t.created_at>= ?',date('Y-m-d H:i:s', strtotime("-{$array['day']} day")));
        if(isset($array['typeId'])) $objs = $objs->andwhere('t.type_id = ?',$array['typeId']);
        if(isset($array['productId']))$objs = $objs->andwhere('t.product_id = ?',$array['productId']);
        if(isset($array['praise']))$objs = $objs->andwhere('t.praise >= ?',$array['praise']);
        if(isset($array['userId']))$objs = $objs->andwhere('t.user_id = ?',$array['userId']);
        if(isset($array['not_id']) && !empty($array['not_id'])) $objs = $objs->andWhere("t.id not in (" . join(",", $array['not_id']) . ") ");
        if(isset($array['arr']))
            return $objs = $objs->fetchArray();
        else
            return $objs = $objs->execute();
    }

    public function getBySql($sql){
        $conn = Doctrine_Manager::getInstance()->getConnection('trade');
        $st = $conn->execute($sql);
        return $st->fetch(Doctrine_Core::FETCH_ASSOC);
    }

    /*
     *获取大于ID条数
     **/
    public static function getCountById($typeId,$productId,$msgCommendId){
        $count = self::getInstance()->createQuery('t')
            ->where('t.status = 1')
            ->andwhere('t.type_id  = ?',$typeId)
            ->andwhere('t.product_id = ?',$productId)
            ->andwhere('t.id <= ? ',$msgCommendId)
            ->count();

        return $count;
    }
}