<?php

/**
 * TrdCabbage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TrdCabbage extends BaseTrdCabbage
{
    public function simpleFormatApp($href="")
    {
        $go_app = sfConfig::get('app_app');
        $data = array();
        $data['id'] = $this->getId();
        $data['title'] = $this->getTitle();
        $data['intro'] = $this->getIntro();
        $data['price'] = $this->getPrice();
        $data['img_path'] = 'http://c'.mt_rand(1, 2).'.hoopchina.com.cn'.$this->getImgPath();
        if($href)
        {
            $data['href'] = $href;
        }else{
            $data['href'] = $go_app['go']['href'].'?url='.urlencode($this->getLinkUrl());
        }
        $data['link_url'] = $this->getLinkUrl();
        return $data;
    }

}
