<?php

/**
 * TrdCollectionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdCollectionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdCollectionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdCollections');
    }

    public function getListById() {
    }

    public function byName($name) {
        return self::getInstance()->createQuery('a')
            ->select('*')
            ->where("shortcut = ?", $name)
            ->fetchOne();
    }

    public function getAll() {
        return self::getInstance()->createQuery('a')
            ->select('*')
            ->orderby("created_at asc")
            ->execute();
    }
}
