<?php

/**
 * TrdCommentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdCommentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdCommentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdCommentType');
    }
}