<?php

/**
 * TrdCollectionItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdCollectionItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdCollectionItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdCollectionItems');
    }

    public function  getByCollectionId($id) {
        $rs = self::getInstance()->createQuery('a')
            ->select('*')
            ->where("collection_id = ?", $id)
            ->orderby("created_at desc")
            ->execute();

        return $rs;
    }

    public function  getCollectionIdByItemAllId($id) {
        $rs = self::getInstance()->createQuery('a')
            ->select('collection_id')
            ->where("item_all_id = ?", $id)
            ->orderby("created_at desc")
            ->fetchArray();

        $ids = array();
        if($rs) {
            foreach($rs as $id) {
                $ids[] = $id["collection_id"];
            }
        }
        return $ids;
    }

    public function add($item_all_id, $collection_id) {
        $TrdCollectionItems = New TrdCollectionItems();
        $TrdCollectionItems->setItemAllId($item_all_id);
        $TrdCollectionItems->setCollectionId($collection_id);
        $TrdCollectionItems->save();
    }

    public function del($item_all_id, $collection_id) {
        return self::getInstance()->createQuery('a')
            ->delete()
            ->where("item_all_id = ? ", $item_all_id)
            ->addWhere("collection_id = ?", $collection_id)
            ->execute();
    }

    public function delAll($item_all_id) {
        return self::getInstance()->createQuery('a')
            ->delete()
            ->where("item_all_id = ? ", $item_all_id)
            ->execute();
    }
}
