<?php

/**
 * TrdClientInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdClientInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdClientInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdClientInfo');
    }
}