<?php

/**
 * trdCommentPraiseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class trdCommentPraiseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object trdCommentPraiseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('trdCommentPraise');
    }

    public  static function getPraise($commentId,$userId){
        return self::getInstance()->createQuery()->where('comment_id = ?',$commentId)->andWhere('user_id = ?',$userId)->fetchOne();
    }
}