<?php

/**
 * TrdFindPraise
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TrdFindPraise extends BaseTrdFindPraise
{

    public function postInsert($event)
    {
        $message = array();
        $message['uid'] = $this->getHupuUid();
        $message['actionid'] = $this->getItemId();
        $message['action'] = "findPraise";
        $this->sendMqMessage($message);
        parent::postInsert($event);
    }

    private function sendMqMessage($message)
    {
        $amqpParams = sfConfig::get("app_mabbitmq_options_shihuo");
        $connection = new AMQPConnection($amqpParams['params']['host'], $amqpParams['params']['port'],$amqpParams['params']['user'], $amqpParams['params']['pass'], $amqpParams['params']['vhost']);
        $channel = $connection->channel();
        $arguments = array(
            "x-dead-letter-exchange" => array("S", "amq.topic"),
            "x-message-ttl" => array("I", 2000),
            "x-dead-letter-routing-key" => array("S", "shihuo.find.praise")
        );
        $channel->queue_declare('shihuo.find.praise.deferred_2', false, true, false, false, false, $arguments);
        $msg = new AMQPMessage(json_encode($message));
        $channel->basic_publish($msg, '', 'shihuo.find.praise.deferred_2');
    }


}
