<?php

/**
 * TrdFeedBackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdFeedBackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdFeedBackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdFeedBack');
    }

    public function shihuoListQuery() {
      return self::getInstance()->createQuery()
              ->where("type = 'shihuo'")
              ->orderBy("id desc");
    }
}
