<?php

/**
 * TrdFindTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdFindTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdFindTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdFindTags');
    }

    /*取tag*/
    public static  function getTags($root_id,$children_id){
        return self::getInstance()->createQuery('a')
            ->select('a.id,a.tags_attr')
            ->where('a.root_id = ?', $root_id)
            ->andWhere('a.children_id = ?', $children_id)
            ->fetchOne();
    }
}