<?php

/**
 * TrdGrouponPraiseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdGrouponPraiseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdGrouponPraiseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdGrouponPraise');
    }
    
    /*
     * 点赞(设备号)
     */
    public static function getAppPraiseInfoByGrouponId($clientcode,$grouponId,$type = 1){
        if (!$clientcode || !$grouponId) return false;
        $query =  self::getInstance()->createQuery('t')
                ->where('t.client_str = ?',$clientcode)
                ->andwhere('t.groupon_id = ?',$grouponId)
                ->andwhere('t.type = ?',$type);
        return  $query->fetchOne();
    }
    
    /*
     * 点赞（用户id）
     */
    public static function getPraiseInfoByGrouponId($uid,$grouponId){
        if (!$uid || !$grouponId) return false;
        $query =  self::getInstance()->createQuery('t')
                ->where('t.client_id = ?',$uid)
                ->addWhere('t.groupon_id = ?',$grouponId)
                ->addWhere('t.is_delete = 0');
        return  $query->fetchOne();
    }

    public function getListByUid($uid)
    {
        return $this->createQuery()
            ->where('client_id = ?', $uid)
            ->addWhere('is_delete = 0')
            ->execute();
    }
}