<?php

/**
 * TrdGoodsAttrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdGoodsAttrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdGoodsAttrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdGoodsAttr');
    }
}