<?php

/**
 * TrdGoodsTagGroupRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdGoodsTagGroupRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdGoodsTagGroupRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdGoodsTagGroupRelation');
    }

    public static function getCategory($groupId = null)
    {
        $connection = Doctrine_Manager::getInstance()->getConnection('trade');

        $query = "select * from trd_goods_tag_group_relation as a join trd_goods_category as b on a.category_id=b.id where a.group_id='{$groupId}'";
        $statement = $connection->execute($query);
        $statement->execute();
        $resultset = $statement->fetchAll(PDO::FETCH_ASSOC);
        return $resultset;
    }

    public static function getGroupByCid($categoryId = null)
    {
        $connection = Doctrine_Manager::getInstance()->getConnection('trade');

        $query = "select a.*,b.name as name,b.id as id,b.value as value,b.click_type from trd_goods_tag_group_relation as a join trd_goods_tag_group as b on a.group_id = b.id where a.category_id='{$categoryId}' and b.status=0";
        $statement = $connection->execute($query);
        $statement->execute();
        $resultset = $statement->fetchAll(PDO::FETCH_ASSOC);
        return $resultset;
    }
}