<?php

/**
 * TrdGoodsTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdGoodsTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdGoodsTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdGoodsTag');
    }
}