<?php

/**
 * TrdGoodsStyleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdGoodsStyleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdGoodsStyleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdGoodsStyle');
    }

    public static function getStyleByName($goods_id,$name)
    {
        return self::getInstance()->createQuery()->andWhere('goods_id=?',$goods_id)->andWhere('name=?',$name)->fetchOne();
    }

    public static function getStyles($goods_id)
    {
        return self::getInstance()->createQuery()->andWhere('goods_id=?',$goods_id)->fetchArray();


    }


    public static function getStylesByFront($goodsId=0)
    {
        $data = CacheModel::getCache();
        if(empty($data))
        {
            $data = self::getInstance()->cureateQuery()->select('id,name,pic,is_default')->andWhere('goods_id = ?',$goodsId)->andWhere('status = 0')->fetchArray();
            CacheModel::setCache($data,60);
        }
        return $data;
    }

    public static function getStylePic($styleId=0)
    {
        $data = CacheModel::getCache();
        if(empty($data))
        {
            $tmp =  self::getInstance()->cureateQuery()->select('value')->andWhere('id = ?',$styleId)->andWhere('status = 0')->fetchArray();
            if(empty($tmp)) return;
            $data = $tmp[0];
            CacheModel::setCache($data,60);
        }
        return $data;
    }
}