<?php

/**
 * TrdGoodsTagGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdGoodsTagGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdGoodsTagGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdGoodsTagGroup');
    }

    public static function houtaGetCount()
    {
        return self::getInstance()->createQuery()->count();
    }


    public static function houtaGetList($offset=0,$limit=20)
    {
        $connection = Doctrine_Manager::getInstance()->getConnection('trade');

        $query = "select a.*,b.name as group_name,b.value as value,c.name as category_name from trd_goods_tag_group_relation as a join trd_goods_tag_group as b on a.group_id = b.id join  trd_goods_category as c on a.category_id = c.id  where b.status=0 order by a.group_id desc";
        $statement = $connection->execute($query);
        $statement->execute();
        $resultset = $statement->fetchAll(PDO::FETCH_ASSOC);

        return $resultset;
    }
}