<?php

/**
 * TrdGoodsNoticeShaiwuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdGoodsNoticeShaiwuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdGoodsNoticeShaiwuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdGoodsNoticeShaiwu');
    }
    public static function houtaGetCount()
    {
        return self::getInstance()->createQuery()->count();
    }


    public static function houtaGetList($offset=0,$limit=20)
    {
        $query = self::getInstance()->createQuery()
            ->orderBy('id desc')
            ->offset($offset)
            ->limit($limit);
        return $query->fetchArray();
    }

    public static function getList($offset,$limit)
    {
        $data = CacheModel::getCache();
        if(empty($data))
        {
            $list = self::getInstance()->createQuery()->offset($offset)->limit($limit)->orderBy('id desc')->fetchArray();
            if(empty($list)) return;
            $ids = array();
            foreach($list as $k=>$v)
            { 
                $ids[] = $v['shaiwu_id'];
            }

            if(!empty($ids))
            {
                $data = trdShaiwuProductTable::getInstance()->createQuery()->select('author_id,author_name,intro,publish_time,img_attr')->andWhereIn('id',$ids)->andWhere('status=1')->orderBy("FIELD(`ID`,".trim(join(",", $ids)) . ')')->fetchArray();
                foreach($data as $k=>$v)
                {
                    $data[$k]['type'] = 1;
                    $pics = json_decode($v['img_attr'],true);
                    if(count($pics)>=3)
                    {
                        $data[$k]['img_attr'] = array_slice($pics,0,3);
                    }
                }
                CacheModel::setCache($data,60);
            }else{
                return;
            }
        }
        return $data;
    }
}