<?php

/**
 * TrdHaitaoOrderHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdHaitaoOrderHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdHaitaoOrderHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdHaitaoOrderHistory');
    }
}