<?php

/**
 * TrdHomepageShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdHomepageShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdHomepageShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdHomepageShop');
    }

    public function getShowList()
    {
        return self::getInstance()->createQuery()
            ->where('status = 0')
            ->orderBy("id desc")
            ->limit(5)
            ->execute();
    }
}
