<?php

/**
 * TrdLottery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    HC
 * @subpackage model
 * @author     HoopChina.com Dev Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TrdLottery extends BaseTrdLottery
{
    public  static $BG_IMG = 'http://c1.hoopchina.com.cn/images/trademobile/choujiang/bg.jpg';
    public  static $POINTER_IMG = 'http://c1.hoopchina.com.cn/images/trademobile/choujiang/start.png';
    public  static $ROUND_IMG = 'http://c1.hoopchina.com.cn/images/trademobile/choujiang/zhuan.png';


    public function getStartTime() {
        $data = $this->_get('start_time');
        return date('Y-m-d H:i:s',$data);
    }

    public function getEndTime() {
        $data = $this->_get('end_time');
        return date('Y-m-d H:i:s',$data);
    }

}
