<?php

/**
 * TrdLotteryHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdLotteryHistoryTable extends Doctrine_Table
{

    public static $SUCC_STATUS = 1;
    public static $NOT_STATUS = 2;




    public static function showVirtualFormat($show_flag,$type = 'string') {
        $string = array(1=>'虚拟',2=>'实物');
        $html_one = array(1=>'<span class="c-green">虚拟</span>',2=>'<span class="c-blue">实物</span>');
        $type = $$type;
        if(!empty($type[$show_flag])) return $type[$show_flag];
        return false;
    }

    public static function showStatusFormat($show_flag,$type = 'string') {
        $string = array(1=>'中',2=>'没中');
        $html_one = array(1=>'<span class="c-green">中</span>',2=>'<span class="c-ccc">没中</span>');
        $type = $$type;
        if(!empty($type[$show_flag])) return $type[$show_flag];
        return false;
    }


    /**
     * Returns an instance of this class.
     *
     * @return object TrdLotteryHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdLotteryHistory');
    }







    /**
     * 获取单个中奖记录
     */
    public static function getOne($bind = array()) {
        $data = self::getAll($bind);
        return $data[0];
    }

    /**
     * 删除数据
     */
    public static function del_one($id) {
        $data = self::getInstance()
            ->createQuery()
            ->select('*')
            ->andWhere('id = ?',$id)
            ->fetchOne();
        if(empty($data)) return false;
        return  $data->delete();
    }

    /**
     * 获取某个会员的卡密记录
     */
    public static function getAll($bind = array()) {
        $data = self::getInstance()->createQuery();
        //select
        if (!empty($bind['select'])){
            $data->select($bind['select']);
        } else {
            $data->select("*");
        }
        //where 简单判断  如果复杂 建议新写函数
        if(!empty($bind['where']) && count($bind['where']) > 0) {
            foreach($bind['where'] as $k=>$v) {
                $data->addWhere($v);
            }
        }
        //whereIn 简单判断  如果复杂 建议新写函数
        if(!empty($bind['whereIn']) && count($bind['whereIn']) > 0) {
            foreach($bind['whereIn'] as $k=>$v) {
                $data->WhereIn($k,$v);
            }
        }
        //order
        if (!empty($bind['order'])){
            $data->orderBy($bind['order']);
        } else {
            $data->orderBy('id desc');
        }
        //limit
        if (!empty($bind['limit'])){
            $data->limit($bind['limit']);
        }
        if(!empty($bind['offset'])) {
            $data->offset($bind['offset']);
        }
        $data =  $data->fetchArray();
        if(!empty($bind['is_count'])) {
            $data = $data[0]['num'];
        }
        return $data;
    }


    //判断今天是否抽奖了
    public static function getTodayCount($lottery_id,$user_id) {
        $data = self::getInstance()->createQuery();
        $data->select('count(id) as num');
        $data->addWhere('lottery_id = ?',$lottery_id);
        $data->addWhere('user_id = ?',$user_id);
        $data->addWhere('created_at >= ?',date("Y-m-d"));
        $data->limit(1);
        $data =  $data->fetchArray();
        $data = $data[0]['num'];
        return $data;
    }




}