<?php

/**
 * TrdMallInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdMallInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdMallInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdMallInfo');
    }

    public function getByDomain($domain) {
        return self::getInstance()->createQuery()
            ->where("domain = ?", $domain)
            ->fetchOne();
    }
}
