<?php

/**
 * TrdNewsZhidingLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdNewsZhidingLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdNewsZhidingLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdNewsZhidingLog');
    }
}