<?php

/**
 * TrdNoticesAttrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdNoticesAttrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdNoticesAttrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdNoticesAttr');
    }

    # 删除评论
    public static function delCommentNotice($comment_id = 0)
    {
        if(empty($comment_id)) return false;
        $comments = self::getInstance()->createQuery()->where('comment_id = ?',$comment_id)->execute();
        if(!empty($comments))
        {
            foreach($comments as $comment)
            {
                $noticeId = $comment->notice_id;
                $comment->delete();
                $notice = TrdNoticesTable::getInstance()->createQuery()->where('id =?',$noticeId)->fetchOne();
                if(!empty($notice)) $notice->delete();
            }
            return true;
        }
        else
        {
            return false;
        }
    }

    # 删除回复
    public static function delReplyNotice($reply_id = 0)
    {
        if(empty($reply_id)) return false;

        $reply = self::getInstance()->createQuery()->where('reply_id =?',$reply_id)->fetchOne();

        if(!empty($reply))
        {
            $noticeId = $reply->notice_id;

            $reply->delete();

            $notice = TrdNoticesTable::getInstance()->createQuery()->where('id = ?',$noticeId)->fetchOne();
            if(!empty($notice)) $notice->delete();
            return true;
        }
        else
        {
            return false;
        }
    }

}