<?php

/**
 * TrdOpenimInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdOpenimInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdOpenimInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdOpenimInfo');
    }
}