<?php

/**
 * TrdRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdRegion');
    }
    
    public static function getByIds($ids) {
      return self::getInstance()
          ->createQuery()
          ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
          ->select('*')
          ->from('TrdRegion')
          ->where("region_id in (" . join(",", $ids) . ") ")
          ->orderBy('region_type asc')
          ->execute();                                                        
    }

    public static function getByPid($pid)
    {
        return self::getInstance()
            ->createQuery()
            ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
            ->select('*')
            ->from('TrdRegion')
            ->where("parent_id =? ",$pid)
            ->orderBy('region_id asc')
            ->fetchArray();
    }



}