<?php

/**
 * TrdSpecialVanclAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdSpecialVanclAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdSpecialVanclAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdSpecialVanclAnswer');
    }
}