<?php

/**
 * TrdTaobaoUrlJumpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdTaobaoUrlJumpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdTaobaoUrlJumpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdTaobaoUrlJump');
    }
    
    public static function getTaobaoItemCount($item_id){
       if (empty($item_id)) return false;
       $query = self::getInstance()->createQuery('m')
                ->where('m.item_id = ?',$item_id);
       return $query->count();     
    }
    public static function getTaobaoItemByItemId($item_id){
        if (empty($item_id)) return false;
        $query = self::getInstance()->createQuery('m')
                    ->where('m.item_id = ?',$item_id);
        return $query->fetchArray();     
    }
}