<?php

/**
 * TrdUserReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdUserReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdUserReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdUserReport');
    }

    function autoSave($item_id) {
        if (sfContext::getInstance()->getUser()->isAuthenticated()) {
            $user_id = sfContext::getInstance()->getUser()->getAttribute('uid');
            if($this->countByUidItemid($user_id, $item_id) == 0) {
                $UserReport = new TrdUserReport();
                $UserReport->setUserId($user_id);
                $UserReport->setItemId($item_id);
                $UserReport->save();
            }
        }
    }

    function countByUidItemid($user_id, $item_id) {
        $count = self::getInstance()->createQuery()
            ->where('user_id=?', $user_id)
            ->addWhere('item_id=?', $item_id)
            ->count();

        return $count;
    }
}
