<?php

/**
 * TrdUserActivityReceiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrdUserActivityReceiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrdUserActivityReceiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrdUserActivityReceive');
    }

    /*
     *获取领取信息
     *
     **/
    public static function getActivityInfo($hupuUid, $userActivityId, $type ){
        $activityInfo = self::getInstance()
            ->createQuery()
            ->where('user_id = ?',$hupuUid)
            ->andWhere('activity_id = ?',$userActivityId);


        if(2 == $type){       //七夕活动，一天一次
            $beforeData =  date('Y-m-d H:i:s',strtotime(date('Y-m-d')));
            $afterData  =  date('Y-m-d H:i:s',strtotime(date('Y-m-d')) + 3600*24);

            $activityInfo = $activityInfo
                ->andWhere('created_at >= ?',$beforeData)
                ->andWhere('created_at < ?',$afterData);
        }

        $activityInfo = $activityInfo->fetchOne();
        if($activityInfo){
            return $activityInfo;
        }else{
            return false;
        }

    }
}