# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .rabbitmq:
    mabbitmq_options:
      params:
        host: 192.168.1.28
        port: 5672
        user: admin
        pass: hcmq1234
        vhost: '/'
      exchanges:
        sms:
          type:     direct
          queue:    smsQueue
          exchange: smsExchange
        ga:
          type:     direct
          queue:    gaQueue
          exchange: gaExchange
        pm:
          type:     direct
          queue:    pmQueue
          exchange: pmExchange
        pm_city:
          type:     direct
          queue:    pm_cityQueue
          exchange: pm_cityExchange
    mabbitmq_options_shihuo:
      params:
        host: 192.168.1.58
        port: 5672
        user: guest
        pass: guest
        vhost: '/'
      exchanges:
        shihuo_item:
          type:     direct
          queue:    shihuo_itemQueue
          exchange: shihuo_itemExchange
        shihuo_find:
          type:     direct
          queue:    shihuo_findQueue
          exchange: shihuo_findExchange
        shihuo_youhui:
          type:     direct
          queue:    shihuo_youhuiQueue
          exchange: shihuo_youhuiExchange
        shihuo_news:
          type:     direct
          queue:    shihuo_newsQueue
          exchange: shihuo_newsExchange
        shihuo_user:
          type:     topic
    mabbitmq_options_kaluli:
      params:
        host: 10.117.207.73
        port: 5672
        user: kaluli
        pass: rvEAZL8oVz9wCM7
        vhost: 'kaluli'

  .api:
    api:
      go:
        url: http://go.shihuo.cn/u
  shihuo_elasticsearch:
     url: http://192.168.1.226:9250
     testurl: http://192.168.1.226:9250
     redis:
       host: 192.168.5.211
       port: 6782
     channel_types:
       youhui: 1
       haitao: 2
       tuangou: 3
       find: 4
       ydx: 5
       daigou: 6
       shaiwu: 7 
       shop: 8
       newfind: 9
       goods: 10
       goods_notice: 11
  kaluli_elasticsearch:
     url: http://10.165.99.244:9250
     testurl: http://10.165.99.244:9250
     channel_types:
       article: 1
       item: 2 
dev:
  .rabbitmq:
    mabbitmq_options:
      params:
        host: 192.168.8.35
        port: 5672
        user: guest
        pass: guest
        vhost: '/'
      exchanges:
        sms:
          type:     direct
          queue:    smsQueue
          exchange: smsExchange
        ga:
          type:     direct
          queue:    gaQueue
          exchange: gaExchange
        pm:
          type:     direct
          queue:    pmQueue
          exchange: pmExchange
        pm_city:
          type:     direct
          queue:    pm_cityQueue
          exchange: pm_cityExchange
    mabbitmq_options_shihuo:
      params:
        host: 192.168.9.91
        port: 5672
        user: shihuoaccess
        pass: shihuoaccess123
        vhost: 'shihuo.hupu.com'
      exchanges:
        shihuo_item:
          type:     direct
          queue:    shihuo_itemQueue
          exchange: shihuo_itemExchange
        shihuo_find:
          type:     direct
          queue:    shihuo_findQueue
          exchange: shihuo_findExchange
        shihuo_youhui:
          type:     direct
          queue:    shihuo_youhuiQueue
          exchange: shihuo_youhuiExchange
        shihuo_news:
          type:     direct
          queue:    shihuo_newsQueue
          exchange: shihuo_newsExchange
        shihuo_user:
          type:     topic
    mabbitmq_options_kaluli:
      params:
        host: 192.168.9.91
        port: 5672
        user: shihuoaccess
        pass: shihuoaccess123
        vhost: 'shihuo.hupu.com'

  .api:
    api:
      go:
        url: http://www.shihuo.cn/u
  #shihuo 调取java数据
  .javaapi:
    javaapi:
      url: http://192.168.8.247:9090
      filter_url: http://192.168.9.129:8083
  shihuo_elasticsearch:
    url: http://192.168.8.179:9250
    testurl: http://192.168.8.179:9250
    redis:
      host: 192.168.8.179
      port: 6379
    channel_types:
      youhui: 1
      haitao: 2
      tuangou: 3
      find: 4
      ydx: 5
      daigou: 6
      shaiwu: 7
      shop: 8
      newfind: 9
      goods: 10
      goods_notice: 11
  kaluli_elasticsearch:
    url: http://192.168.8.179:9250
    testurl: http://192.168.8.179:9250
    channel_types:
      article: 1
      item: 2
  kaola:
    open_api_url: https://openapi.kaola.com
    code_url: https://oauth.kaola.com/oauth/authorize
    access_token_url: http://partner.kaola.com
  jd:
    open_api_url: https://api.jd.com/
stg:
  .rabbitmq:
    mabbitmq_options:
      params:
        host: 192.168.8.35
        port: 5672
        user: guest
        pass: guest
        vhost: '/'
      exchanges:
        sms:
          type:     direct
          queue:    smsQueue
          exchange: smsExchange
        ga:
          type:     direct
          queue:    gaQueue
          exchange: gaExchange
        pm:
          type:     direct
          queue:    pmQueue
          exchange: pmExchange
        pm_city:
          type:     direct
          queue:    pm_cityQueue
          exchange: pm_cityExchange
        shihuo_item:
          type:     direct
          queue:    shihuo_itemQueue
          exchange: shihuo_itemExchange
    mabbitmq_options_shihuo:
      params:
        host: 192.168.9.91
        port: 5672
        user: shihuoaccess
        pass: shihuoaccess123
        vhost: 'shihuo.hupu.com'
      exchanges:
        shihuo_item:
          type:     direct
          queue:    shihuo_itemQueue
          exchange: shihuo_itemExchange
        shihuo_find:
          type:     direct
          queue:    shihuo_findQueue
          exchange: shihuo_findExchange
        shihuo_youhui:
          type:     direct
          queue:    shihuo_youhuiQueue
          exchange: shihuo_youhuiExchange
        shihuo_news:
          type:     direct
          queue:    shihuo_newsQueue
          exchange: shihuo_newsExchange
        shihuo_user:
          type:     topic
    mabbitmq_options_kaluli:
      params:
        host: 10.171.201.113
        port: 5672
        user: kaluli
        pass: rvEAZL8oVz9wCM7
        vhost: 'kaluli'
  kaluli_elasticsearch:
     url: http://10.165.98.176:9200
     testurl: http://10.165.98.176:9200
     channel_types:
       article: 1
       item: 2

    
all:
  trade:
    qiniu:
      bucket: hupu-shihuo
      accessKey: O5OQnIPVV8y1cBmLn8yeaH58QjJ2kHLxB-mbcG5R
      secretKey: dLoulit_AazujFZRxPLSpOTBW_ht5IYRCDVsNbn-
      uploadHost: https://shihuo.hupucdn.com/
    
  .api:
    api:
      go:
        url: http://go.shihuo.cn/u   
  .javaapi:
    javaapi:
      url: http://192.168.1.197:8080
      filter_url: http://192.168.1.197:8081
  .url:
    gamespace_url: http://g.hupu.com/nba
    shihuo_url: http://www.shihuo.cn
  kaola:
    open_api_url: https://openapi.kaola.com
    code_url: https://oauth.kaola.com/oauth/authorize
    access_token_url: http://partner.kaola.com
  jd:
    open_api_url: https://api.jd.com/ 
  kaluli_qianniu:
    appkey: 23263747
    sercrt: a2d059426adbbb789ff2375ae5ab627b
  

  doc:
    #直邮报关id和商品条形码对应关系,字典表type为1
    zhiyou: 1
  log_srv: http://point.kaluli.com/userLog
