listSuccess:
  javascripts:
    - http://kaluli.hoopchina.com.cn/js/trade/index.js
  stylesheets: 
    - http://kaluli.hoopchina.com.cn/css/trade/zbq_common.css
    - http://kaluli.hoopchina.com.cn/css/trade/proIframe.css

gamePageSuccess:
  stylesheets:
    - http://kaluli.hoopchina.com.cn/css/trade/1111/flip.css
    - http://kaluli.hoopchina.com.cn/css/trade/1111/style.css
  javascripts:
    - http://kaluli.hoopchina.com.cn/js/trade/1111/jquery-1.11.1.min.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/handlebars-v2.0.0.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/jquery.countdown.min.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/jquery.share.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/double11.js
  metas:
    title: 识货 - 天猫年中大促
    X-UA-Compatible: IE=edge;chrome=1
gameBBsPageSuccess:
  stylesheets:
    - http://kaluli.hoopchina.com.cn/css/trade/1111/flip.css
    - http://kaluli.hoopchina.com.cn/css/trade/1111/style.css
  javascripts:
    - http://kaluli.hoopchina.com.cn/js/trade/1111/jquery-1.11.1.min.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/handlebars-v2.0.0.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/jquery.countdown.min.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/jquery.share.js
    - http://kaluli.hoopchina.com.cn/js/trade/1111/double11.js
  metas:
    title: 识货 - 天猫年中大促
    X-UA-Compatible: IE=edge;chrome=1
  has_layout:     false
gamePageMobileSuccess:
  has_layout:     false
gouSuccess:
  javascripts: 
  stylesheets: 
    - trade/apigou/api-gou.css
  metas:
    title: 海淘代购列表
qixiSuccess:
  javascripts:     
  stylesheets: [http://www.shihuo.cn/css/trade/activity/qixi.css,http://www.shihuo.cn/css/trade/activity/qixi-sprites-icon.css,http://www.shihuo.cn/css/video/projekktor.style.css]
  metas:
    title: 识货七夕女王评选，来就送券，更有全场满减。赶紧来参加吧 - 识货