# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  style_version: 20170908_02
  config:
    title: 财审后台
    url:  http://www.shihuo.cn/
    m_url: http://m.shihuo.cn/
  kll:
    erp_type: Edb
    edb_config:
      server: http://vip532.edb05.com/rest/index.aspx
      dbhost: edb_a84292g
      appkey: 7d4aba5b
      format: JSON
      appscret: ac9e91e7622e4656834f10a94e56de8c
      token: 9fd1ac5bc22e4604841291b063366d0a
      slencry: 0
      v: '2.0'
    edb_dev_config:
      server: http://vip802.6x86.com/edb2/rest/index.aspx
      dbhost: edb_a88888
      appkey: 6f55e36b
      format: JSON
      appscret: adeaac8b252e4ed6a564cdcb1a064082
      token: a266066b633c429890bf4df1690789a3
      slencry: 0
      v: '2.0'
  codeConfig:
    def_ajax_type: JSON
    jsonp_handeler: callback
    # RBAC
    user_auth_on: 1
    user_auth_type: 1
    # 公共控制器 或者方法 必须 全部转换成！小！写！ 你方法如果是大小写字母混合  一定要转换成小写！！
    public_auth_action:
      0: public/login
      1: public/logout
      2: public/welcome
      3: trd_menu/getchildrenmenusbyid
      4: trd_store/getstorebytype
      5: trd_news/crawler
      6: trd_news/ajaxgetbrands
      7: trd_seo_news/*
      8: trd_news/gettagbymodelid
      9: trd_news/getnewattributebychildrenid
      10: trd_news/getmodelbybrandid
      11: trd_news/savebrandtype
      12: trd_news/savemodel
      13: trd_news/savetag
      14: trd_api/elasticJoinSet
   # 不用登录就可以访问的公共方法  也必须全部转换成小写 也支持  *
    no_login_action:
      0: public/login
      1: public/bfapi
      2: trd_goods/relation
      3: trd_goods_supplier/add
      4: trd_goods/ajaxrealtionlist
    express_for_ware:
      1: '申通',
      2: '顺丰',
      3: 'EMS',
      4: '圆通',
      5: '韵达',
      6: '中通',
      7: '天天快递',
      8: '汇通',
      9: '宅急送',
      33: '速尔',
      28: '其他',
   

  trade:
    model_cache_ttl: 1800
    cache_server_ip: 192.168.1.92
    cache_server_port: 11200
    send_message_for_order_nan_sha: http://api.ranshaozhifang.com/nsapi/synApi/updateOrderSynApi
    brid_api_url: http://birdex.ranshaozhifang.com
    nasha_api_url: http://api.ranshaozhifang.com/nsapi
  log_record:
      modules:
        log1: kaluli_lipinka
        log2: kaluli_order
        log3: kaluli_item
        log4: kaluli_item_sku


dev:
  trade:
    model_cache_ttl: 1800
    cache_server_ip: 192.168.8.193
    cache_server_port: 11211
    promote_dace_1111: http://192.168.8.83:8080/dace-api
    promote_dace_blackfive: http://192.168.8.83:8080
    send_message_for_order_nan_sha: http://192.168.11.28:8080/kaluli/synApi/updateOrderSynApi
    bird_api_url: http://birdex.ranshaozhifang.com
    nasha_api_url: http://192.168.11.28:8080/nsapi



