# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  style_version: 2016031606
  app_style_version: 2016031606


  ban:
    time: 1 # 1 day

  home:
    url: http://www.shihuo.cn

   # Configs used by cron tasks
  .tasks:
    tasks:

  .credentials:
    credentials:
      imikay: [moderator]
      Trip_hop: [moderator]
      harbuzi: [moderator]
      autohao: [moderator]
      狮王LEO: [moderator]
      ye_wa: [moderator]
      dunk96: [moderator]
      虎扑装备区: [moderator]
      vitohe: [moderator]
      wumengmeng1010: [moderator]
      webstarting: [moderator]
      今天星期四: [moderator]

  # Configs for API
  .api:
    api:
      pm:
        url: http://my.hupu.com/api/sendmsg.api.php
      go:
        url: http://go.shihuo.cn/u
      taobao_item_detail:
        url: "http://detailskip.taobao.com/json/ifq.htm?callback=shihuo&sid=1&q=1&id="
      kaluli:
        url: http://my.hupu.com/api/money.api.php
    app:
      go:
        href: shihuo://go
  .zb:
    zb:
      homeurl: http://zb.hupu.com
  itemList:
    maxPerPage: 150
    maxPerScreen: 20
  .dace_api:
    dace_api:
      url: http://dace-api.jh.hupu.com:8080
  .javaapi:
    javaapi:
      url: http://192.168.1.197:8080
      filter_url: http://192.168.1.197:8081

  img_dir:
    tmp_pwd: %SF_UPLOAD_DIR%/trade/tmp/
    tmp_show: /uploads/trade/tmp/
    real_pwd: %SF_UPLOAD_DIR%/trade/items/
    real_show: /uploads/trade/items/
    web: %SF_WEB_DIR%

  .report:
    report:
      1: "价格信息不符"
      2: "产品图与产品信息有差别"
      3: "商家假货"
      4: "其他原因"

  .message:
    message:
      sender:
        uid: 16137597
        username: 虎扑新装备
      ban:
        subject: 你被封禁了
        message: >
          {{hupuUsername}}：您在发布{{itemName}}时，违反了识货发布规范(http://bbs.hupu.com/3794047.html)，
          因此被{{days}}。请您能够严格遵守识货版规的小小要求(http://bbs.hupu.com/3794047.html)，
          相信您一定会在识货收获更多。如果封禁有误，请至 http://bbs.hupu.com/gearfeedback 投诉。

      unban:
        subject: 你被解禁了
        message: >
          {{hupuUsername}}：您在识货已经被解封，欢迎回来，识货将更好的为您服务。

   # API accounts
  .yiqifa:
    yiqifa:
      key: 13476095846425253
      secret: 187754c61d925a50b5862123472bb3f7
  .feedback:
    feedback:
      content_length: 1000
  .lefttime:
    lefttime:
      taobaogotocache: 86400

  #weibo
  weibo:
    appakey: 3033141272
    appskey: adfe3ccf35462bedd454b9800abe5b3e
    callback: http://www.shihuo.cn/weibo/callback

  #the total commemt
  comment:
    appid: 12
  comment_seo:
    appid: 25

  limitusers:
      ids: [17680433, 16511285, 4623204, 5178304, 15461283, 3140268, 17605765, 17619214, 193865, 17337327, 17191627, 17710630, 17710803, 17710744, 3140805, 17752943, 16377341, 15524964, 17077204, 16940627]
      recommend_ids: [5178304, 17191627]
  trade:
    model_cache_ttl: 1800
    cache_server_ip: 192.168.1.92
    cache_server_port: 11200
    promote_dace_1111: http://dace-api.jh.hupu.com:8080
    promote_dace_blackfive: http://dace-api.jh.hupu.com:8080
  dace_statistics:
    chuchuang: chuchuang
    zhuanti: zhuanti
    rebang: rebang
    faxian: faxian
    tuangou: tuangou
    youhui_zhiding: youhui_zhiding
    zuocedaohang: zuocedaohang
    gonglue: gonglue
    find_goods: find_goods
    find_goods_detail: find_goods_detail
    find_shoes: find_shoes
    find_shoes_detail: find_shoes_detail
    tuangou_list: tuangou_list
    shoe_index:
      biaoqian_remen: biaoqian&type=remen&order=
      biaoqian_qiuxie: biaoqian&type=qiuxie&order=
      biaoqian_jiage: biaoqian&type=jiage&order=
      banner: banner&order=
      brand_pic: brand_pic
      product_pic: product_pic
      tuijian: tuijian&order=
    shoe_list:
      shoe_list: shoe_list
      shoe_hot: shoe_hot&order=
      shoe_people: shoe_people&order=
    shoe_detail:
      detail_brand: detail&type=brand
      detail_product: detail&type=product
      tuijian_people: tuijian_people&order=
      tuijian_brand: tuijian_brand&orde=
      tuijian_price: tuijian_price&orde=
    find_index:
      biaoqian_hot: biaoqian&type=hot&order=
      banner: banner&order=
    find_detail:
      detail_brand: detail&type=brand
      detail_product: detail&type=product
      tuijian: qk=tuijian&order=
  groupon:
    alliance_price: 5000
    putaway_price: 500
    mini_putaway_price: 350
    ad_price: 300
  cacheOffset:
    shaiwuList: 'shaiwuListOffset',
dev:
  .credentials:
    credentials:
      imikay: [moderator]
      wumengmeng1010: [moderator]
      webstarting: [moderator]
  .api:
    api:
      go:
        url: http://www.shihuo.cn/u
    app:
      go:
        href: shihuo://go

  itemList:
    maxPerPage: 100
  .dace_api:
    dace_api:
      url: http://192.168.8.83:8080
  .javaapi:
    javaapi:
      url: http://192.168.8.247:9090
      filter_url: http://192.168.9.129:8083
  groupon:
    alliance_price: 0.1
    putaway_price: 0.3
    mini_putaway_price: 0.2
    ad_price: 0.1
  trade:
    model_cache_ttl: 1800
    cache_server_ip: 192.168.8.193
    cache_server_port: 11211
    promote_dace_1111: http://192.168.8.83:8080/dace-api
    promote_dace_blackfive: http://192.168.8.83:8080
