---
options:
  collate: utf8_general_ci
  charset: utf8
  type: InnoDB

KllBBMainOrder:
  tableName: kll_main_order
  connection: kaluliBB
  columns:
    id:                 { type: integer, unsigned: true, primary: true, autoincrement: true }
    order_number  :     { type:  varchar(255) }
    origin_order_number: { type: varchar(255) }
    total_price :       { type:  float, length: 8, scale: 2 }
    push_price  :       { type:  float, length: 8, scale: 2 }
    real_price  :       { type:  float, length: 8, scale: 2 }
    express_fee :       { type:  float, length: 8, scale: 2 }
    duty_fee  :         { type:  float, length: 8, scale: 2 }
    coupon_fee  :       { type:  float, length: 8, scale: 2 }
    pay_status  :       { type:  tinyint(2) }
    pay_type  :         { type:  tinyint(2) }
    pay_time  :         { type:  integer(11), unsigned: true }
    uid  :              { type:  integer(10), unsigned: true }
    status  :           { type:  tinyint(2), unsigned: true }
    logistic_type:      { type:  tinyint(3), unsigned: true }
    logistic_number:    { type:  varchar(255) }
    flow_number:        { type:  varchar(255) }
    payer:              { type:  varchar(255) }
    source  :           { type:  varchar(255) }
    batch:              { type:  varchar(255) }
    syn_api:            { type:  tinyint(3) }
    count  :            { type:  integer(5), unsigned: true }
    audit_time  :       { type:  integer(11), unsigned: true }
    creat_time  :       { type:  integer(11), unsigned: true }
    update_time :       { type:  integer(11), unsigned: true }

KllBBMainOrderAttr:
  tableName: kll_main_order_attr
  connection: kaluliBB
  columns:
    id :                { type: int(10), unsigned: true, primary: true, autoincrement: true }
    order_number:       { type:  varchar(255) }
    province:           { type:  varchar(255)  }
    city:               { type:  varchar(255) }
    area:               { type:  varchar(255) }
    address:            { type: varchar(255)  }
    real_name:          { type: varchar(255) }
    account:            { type: varchar(255) }
    receiver:           { type: varchar(255) }
    mobile:             { type:  bigint(20) }
    logistic_number:    { type: int(10) }
    postal_code:        { type: int(5)  }
    card_type:          { type: varchar(255) }
    card_code:          { type: varchar(255) }
    creat_time:         { type:  int(11) }
    update_time:        { type: int(11) }

KllBBOrder:
  tableName: kll_order
  connection: kaluliBB
  columns:
    id:                     { type:  int(10), unsigned: true, primary: true, autoincrement: true }
    order_number:           { type:  varchar(255) }
    child_order_number:     { type:  varchar(255) }
    name:                   { type:  varchar(255) }
    description:            { type:  varchar(255) }
    receiver:               { type:  varchar(255) }
    product_code:           { type:  varchar(255) }
    product_id:             { type:  varchar(255) }
    goods_id:               { type:  int(11) }
    total_price:            { type: float(8), length: 8, scale: 2  }
    pay_time:               { type:  int(10) }
    pay_status:             { type:  tinyint(5)  }
    price:                  { type: float(8), length: 8, scale: 2  }
    number:                 { type:  int(5)  }
    batch:                  { type: varchar(255) }
    update_time:            { type: int(11) }
    creat_time:             { type:  integer(11) }
    ware_status:            { type: tinyint(2) }
    status:                 { type: tinyint(2) }
    ware_house:             { type: tinyint(3) }

KllBBOrderFlow:
  tableName: kll_order_flow
  connection: kaluliBB
  columns:
      flow_number:  { type: varchar(20), unsigned: true } 
      body:         { type: text } 
      creat_time:   { type: int(11) }
      update_time:  { type: int(11) }

KllBBOrderLog:
  tableName: kll_order_log
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true }
    order_number:     { type:  varchar(255) }
    type:             { type: tinyint(2) }
    content:          { type: text }
    creat_time:       { type: int(10), unsigned: true }
    update_time:      { type: integer(10), unsigned: true }
    operation_user:   { type: int(10), unsigned: true }

KllBBOrderFile:
  tableName: kll_order_file
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true  }
    source:           { type:  varchar(50)}
    uid :             { type: integer(11), unsigned: true }
    file:             { type: varchar(255) }
    number:           { type: integer(10) }
    status:           { type: tinyint(3), unsigned: true }
    surplus:          { type: tinyint(3), unsigned: true }
    batch:            { type: varchar(255) }
    creat_time:       { type: integer(11),  unsigned: true }
    update_time:      { type: integer(11),  unsigned: true }

KllBBOrderSynApi:
  tableName: kll_order_syn_api
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true  }
    zt:               { type: integer(11), unsigned: true }
    order_number:     { type: varchar(255) }
    send_gj:          { type: integer(11), unsigned: true }
    send_gj_date:     { type: timestamp } 
    send_hg:          { type: integer(11), unsigned: true }
    send_hg_date:     { type: timestamp } 
    send_zz:          { type: integer(11), unsigned: true }
    send_zz_date:     { type: timestamp } 
    syn_date:         { type: timestamp } 
    send_yb_gj:       { type: integer(11), unsigned: true }
    send_yb_gj_date:  { type: timestamp } 
    logisticJSON:     { type: varchar(500) }
    send_yb_hg:       { type: integer(11), unsigned: true }
    send_yb_hg_date:  { type: timestamp }
    pay_type:         { type: integer }
    send_nr:          { type: integer }
    send_nr_date:     { type: timestamp }
    source:           { type: varchar(100) }
    edi_orderno:      { type: varchar(100) }
    send_jd_pay:      { type: integer }
    send_jd_pay_date: { type: timestamp }

KllBBMq:
  tableName: kll_mq
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true  } 
    msg_type:         { type: varchar(255) } 
    msg_id:           { type: varchar(255) }
    msg_channel:      { type: varchar(255) }
    msg_body:         { type: text }
    msg_status:       { type: integer(11), unsigned: true }
    order_number:     { type: varchar(255) }
    zt:               { type: integer(11), unsigned: true }
    msg_time:         { type: timestamp }
    msg_response:     { type: text }
    notify_response:  { type: text }   
KllErpSkuPrice:
  tableName: kll_erp_sku_price
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true  } 
    goods_id:         { type: integer(11), unsigned: true }
    sku_id:           { type: integer(11), unsigned: true }
    code_num:         { type: varchar(50) } 
    product_code:       { type: varchar(50) } 
    goods_title:      { type: varchar(255) }
    channel:          { type: varchar(255) }
    depot:            { type: tinyint(3) }
    standard_price:   { type: float, length: 8, scale: 2 }
    cost_price:       { type: float, length: 8, scale: 2 }
    push_price:       { type: float, length: 8, scale: 2 }
    add_user:         { type: integer(11), unsigned: true }
    audit_user:       { type: integer(11) }
    audit_status:     { type: tinyint(3) }
    audit_time:       { type: integer(11) }
    create_time:      { type: integer(11) }
    update_time:      { type: integer(11) }
KllErpOrder:
  tableName: kll_erp_order
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true  } 
    order_number:     { type: varchar(255), unsigned: true }
    audit_status:     { type: tinyint(3) }
    channel:          { type: varchar(255) }
    audit_user:         { type: integer(11), unsigned: true }
    audit_time:       { type: integer(11) }
    create_time:      { type: integer(11) }
    update_time:      { type: integer(11) }
KllErpOrderExplain:
  tableName: kll_erp_order_explain
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true  } 
    order_number:     { type: varchar(255), unsigned: true }
    remark:           { type: text  }
    pic:              { type: text }
    type:             { type: tinyint(2) }
    user:             { type: integer(11), unsigned: true }
    create_time:      { type: integer(11) }
KllBBProcess:
  tableName: kll_bb_process
  connection: kaluliBB
  columns:
    id:               { type:  int(10), unsigned: true, primary: true, autoincrement: true  } 
    order_number:     { type: varchar(255), unsigned: true }
    content:          { type: text  }
    sequence:         { type: tinyint(2) }
    status:           { type: tinyint(2) }
    update_time:      { type: integer(11), unsigned: true }
    create_time:      { type: integer(11) }
